import {transportLinks} from './travel-links.js';
import {escapeText as esc} from './explore.js';
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n||0)/100);
async function request(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json'}});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to retrieve booking details.');return d;}
export function policyMarkup(b){
 const p=b.cancellation_policy;if(b.payment_policy_version!==2||!p)return '<p>Your original quotation terms apply. Contact support for cancellation details.</p>';
 return `<section class="deposit-policy"><h3>20% booking deposit · 80% after check-in</h3><p>The deposit counts toward your trip total; it is not an extra charge. The balance opens after operator-verified check-in.</p><p>Scheduled check-in: <strong>${esc(new Date(b.checkin_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}))} IST</strong></p><h4>Cancellation deductions from the deposit</h4><ul>${p.graceHours>0?`<li>Within ${p.graceHours} hours of deposit capture, and more than 24 hours before check-in: ${p.gracePercent}% of the deposit.</li>`:''}<li>Otherwise, more than 7 days before check-in: ${p.earlyPercent}%.</li><li>More than 24 hours and up to 7 days before check-in: ${p.middlePercent}%.</li><li>Within 24 hours before check-in: ${p.latePercent}%.</li></ul><p>After the scheduled check-in time, contact support. Any refundable remainder is processed after reconciliation; recording a cancellation does not mean a refund has already reached your account.</p></section>`;
}
export function mountBookingActions(main,b){
 const target=main.querySelector('.account-content')||main;const box=document.createElement('section');box.className='booking-next-actions';
 box.innerHTML=(b.itinerary?.length?`<section class="deposit-policy"><h3>Your requested itinerary</h3><ol>${b.itinerary.map(line=>`<li>${esc(line)}</li>`).join('')}</ol><p>Requested activities remain subject to your final quotation.</p></section>`:'')+policyMarkup(b)+`<div class="journal-actions"><a class="button outline" href="#/confirmation/${b.id}">Booking confirmation ↗</a>${b.payment_policy_version===2&&!b.cancellation_requested_at?`<a class="underlined" href="#/cancellation-request/${b.id}">Review cancellation</a>`:''}${b.checked_in_at&&!b.balance_paid_at&&!b.cancellation_requested_at?`<a class="button" href="#/checkout/${b.id}?purpose=balance">Pay remaining 80% ↗</a>`:''}</div>${b.balance_paid_at?'<p>Balance payment received.</p>':''}${b.cancellation_requested_at?`<p>Cancellation recorded. Deduction: ${money(b.cancellation_fee_paise)}. Refundable remainder: ${money(b.cancellation_refund_paise)} — check payment history for processing status.</p>`:''}${transportLinks()}`;target.append(box);
}
export async function bookingFlowPage(route,id,main){
 const hash=location.hash;const {booking:b}=await request('/api/bookings?id='+encodeURIComponent(id||''));if(location.hash!==hash)return;
 if(route==='cancellation-request'){
  let preview;try{preview=await request('/api/config?service=trip-actions&bookingId='+encodeURIComponent(id));}catch(e){if(location.hash===hash)main.innerHTML=`<section class="wrap account-required"><h1>Cancellation<br><em>review.</em></h1><p>${esc(e.message)}</p><a class="button" href="#/booking/${b.id}">Back to booking</a> <a class="underlined" href="#/contact">Contact support</a></section>`;return;}
  if(location.hash!==hash)return;const c=preview.cancellation;
  main.innerHTML=`<section class="wrap account-page"><span class="eyebrow green">YOUR BOOKING / CANCELLATION</span><h1>${esc(b.destination_name)}</h1><p>Review the deduction before confirming. Amounts are calculated from your recorded deposit and the quotation’s saved policy.</p>${policyMarkup(b)}<dl class="cancellation-totals"><div><dt>Deposit received</dt><dd>${money(c.deposit??Number(b.cancellation_fee_paise)+Number(b.cancellation_refund_paise))}</dd></div><div><dt>Cancellation deduction${c.percent!==undefined?' ('+c.percent+'%)':''}</dt><dd>${money(c.deduction)}</dd></div><div><dt>Refundable remainder</dt><dd>${money(c.refund)}</dd></div></dl>${c.recorded?'<p role="status">Cancellation already recorded. Any refundable amount is awaiting or undergoing processing; see payment history.</p>':`<form class="account-form" id="cancel-trip-form"><label>Reason (optional)<textarea name="reason" maxlength="1000"></textarea></label><label class="check-row"><input name="accept" type="checkbox" required>I want to cancel this trip and accept the displayed deduction from my deposit.</label><button class="button">Confirm cancellation</button><p class="form-status" role="status"></p></form>`}<a class="underlined" href="#/booking/${b.id}">Back to booking ↗</a></section>`;
  const form=main.querySelector('form');if(form)form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;try{await request('/api/config?service=trip-actions',{method:'POST',body:JSON.stringify({bookingId:b.id,action:'cancel',reason:new FormData(form).get('reason'),accept:true,expectedFee:c.deduction})});if(location.hash===hash)await bookingFlowPage(route,id,main);}catch(error){form.querySelector('.form-status').textContent=error.message;button.disabled=false;}};return;
 }
 const {payments}=await request('/api/payments');if(location.hash!==hash)return;const own=payments.filter(p=>p.booking_id===b.id),deposit=own.find(p=>p.purpose==='deposit'&&p.status==='captured'),balance=own.find(p=>p.purpose==='balance'&&p.status==='captured');
 const cancelled=b.status==='cancelled',confirmed=!!b.confirmed_at&&!cancelled;
 main.innerHTML=`<section class="wrap account-page confirmation-page"><span class="eyebrow green">${route==='thank-you'?'THANK YOU / YOUR NEXT CHAPTER':'BOOKING CONFIRMATION'}</span><h1>${cancelled?'Cancellation recorded.':confirmed?'Your booking is confirmed.':deposit?'Thank you.<br><em>Your deposit is received.</em>':'Your trip request<br><em>is in progress.</em>'}</h1><p>${cancelled?'Review the cancellation and refund details in your account.':confirmed?'Your travel team has recorded supplier confirmation.':deposit?'Supplier confirmation is still pending. We will update your booking after the remaining checks.':'No captured deposit or confirmed reservation has been recorded yet.'}</p><div class="company-card"><h2>${esc(b.destination_name)}</h2><p>Booking reference: ${esc(b.id)}</p><p>${b.days} days · ${b.travelers} travelers</p><p>Deposit: ${deposit?money(deposit.amount_paise)+' received':'Not captured'}</p><p>Check-in: ${b.checked_in_at?'Verified by your operator':'Not yet recorded'}</p><p>Balance: ${balance?money(balance.amount_paise)+' received':'Due after check-in under your quotation terms'}</p><a class="button" href="#/booking/${b.id}">Manage trip ↗</a> <a class="underlined" href="#/payments">Payment history</a></div>${transportLinks()}</section>`;
}
