import {mountSocialLinks,transportLinks} from './travel-links.js';
import { partnerStays, careerOpenings, campingKits } from './partner-data.js';
import { escapeText as esc } from './explore.js';
export const companyRoutes=new Set(['careers','sponsors','partnerships','stays','camping','contact','enquiry-inbox']);
const hero=(tag,title,copy)=>`<section class="page-intro wrap"><a class="back-link" href="#/">← KuboVistas</a><span class="eyebrow green">${tag}</span><h1>${title}</h1><p>${copy}</p></section>`;
const contact=(kind,label,subject='')=>`<a class="button" href="#/contact?kind=${kind}&subject=${encodeURIComponent(subject)}">${label} ↗</a>`;
const cards=items=>`<div class="company-grid">${items.map(([tag,title,copy])=>`<article class="company-card"><span class="eyebrow green">${tag}</span><h2>${title}</h2><p>${copy}</p></article>`).join('')}</div>`;
const banner=(title,copy,cta)=>`<section class="company-banner"><div><h2>${title}</h2><p>${copy}</p></div>${cta}</section>`;
async function service(name,options={}){const r=await fetch('/api/config?service='+name,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json'}});const d=await r.json();if(!r.ok)throw Error(d.error||'Service unavailable');return d;}
export async function companyPage(route,main){
 document.title=`${({careers:'Careers',sponsors:'Sponsorship',partnerships:'Partnerships',stays:'Partner stays',camping:'Camping & trekking kits',contact:'Contact', 'enquiry-inbox':'Enquiry inbox'})[route]} — KuboVistas`;
 if(route==='contact')return contactPage(main);
 if(route==='enquiry-inbox')return inbox(main);
 if(route==='careers'){
 main.innerHTML=hero('CAREERS / BUILD WITH US','Good journeys start<br>with <em>good people.</em>','Help shape thoughtful travel through clear information, local relationships and attentive service.')+`<section class="wrap section top-tight">${cards([['OUR WORK','Travel, with purpose.','We value careful research, respectful storytelling and practical help for travelers.'],['OUR APPROACH','People before promises.','Bring curiosity, clear communication and a willingness to verify details before sharing them.'],['YOUR CONTRIBUTION','A place for your strengths.','Tell us about your experience in travel operations, writing, design, technology or host relationships.']])}<div class="company-section-heading"><span class="eyebrow green">CURRENT OPPORTUNITIES</span><h2>Find your next chapter.</h2></div>${careerOpenings.length?careerOpenings.map(r=>`<article class="company-card"><span>${esc(r.location)} · ${esc(r.type)}</span><h3>${esc(r.title)}</h3><p>${esc(r.description)}</p>${contact('career','Enquire about this role',r.title)}</article>`).join(''):'<div class="company-empty"><h3>No open roles have been announced.</h3><p>You can send an expression of interest with your area of work and a public portfolio link. This does not represent an advertised vacancy or an employment offer.</p></div>'}${banner('Introduce yourself.','Share the work you are proud of and how you would like to contribute.',contact('career','Send an expression of interest'))}</section>`;return;
 }
 if(route==='sponsors'){
 main.innerHTML=hero('SPONSOR KuboVistas','Support the stories.<br><em>Join the journey.</em>','Explore relevant sponsorships that help travelers discover places thoughtfully, with clear disclosure and agreed deliverables.')+`<section class="wrap section top-tight">${cards([['EDITORIAL','Destination storytelling','Discuss a clearly labeled sponsored article, useful travel guide or responsibly produced destination feature.'],['CAMPAIGNS','Shared travel moments','Propose a relevant seasonal campaign across agreed KuboVistas channels. Scope, approvals and measurement are settled in writing.'],['EQUIPMENT','Support the outdoors','Discuss an equipment collaboration with a clear usage plan, product information and honest disclosure.']])}<div class="company-process"><h2>From first conversation<br>to <em>clear agreement.</em></h2><ol><li>Tell us your brand, goals and intended audience.</li><li>Agree on scope, budget, permissions and editorial boundaries.</li><li>Approve a written schedule and disclosure requirements.</li><li>Review the agreed deliverables and available campaign results.</li></ol></div>${banner('A fit worth exploring?','No audience size, reach or sponsorship results are guaranteed. A proposal is not an accepted campaign.',contact('sponsor','Discuss sponsorship'))}</section>`;return;
 }
 if(route==='partnerships'){
 main.innerHTML=hero('PARTNERSHIPS / LOCAL CONNECTIONS','Better together.<br><em>Better for the journey.</em>','We welcome conversations with accommodation providers, local guides and responsible outdoor operators.')+`<section class="wrap section top-tight">${cards([['STAY PARTNERS','Hotels, homestays & hostels','Share your property location, room types, facilities, accessibility, policies and authorized business contact.'],['LOCAL EXPERTS','Guides & experiences','Tell us your service area, qualifications where applicable, group limits and how you manage changing conditions.'],['OUTDOOR PARTNERS','Camping & trekking support','Share equipment specifications, maintenance practices, route expertise, rental terms and permitted operating areas.']])}<div class="company-process"><h2>Trust begins<br>with <em>the details.</em></h2><ol><li>Send your business introduction and public website or profile.</li><li>We review fit, location, service information and permissions.</li><li>Agree written responsibilities, prices and cancellation terms.</li><li>Publish approved information after partnership confirmation.</li></ol><p>Submitting a proposal does not create a partnership or guarantee a listing. Do not send identity documents through this form.</p></div>${banner('Let’s get acquainted.','We list confirmed partners only, with permission and accurate information.',contact('partnership','Introduce your business'))}<a class="underlined" href="#/stays">Explore the partner stay directory ↗</a></section>`;return;
 }
 if(route==='stays'){
 main.innerHTML=hero('PARTNER STAYS','A place to stay.<br><em>A reason to linger.</em>','Explore confirmed hotel, homestay and hostel partners as they join the KuboVistas directory.')+`<section class="wrap section top-tight"><div class="stay-filters"><label>Stay type<select id="stay-type"><option>All stays</option><option>Hotel</option><option>Homestay</option><option>Hostel</option></select></label><label>Search destination or property<input type="search" id="stay-search" placeholder="Where would you like to stay?"></label></div><p id="stay-count" role="status"></p><div class="company-grid" id="stay-results"></div>${banner('Looking for the right base?','Share your dates, destination, party size and accommodation preferences. Availability and prices require a confirmed quotation.',contact('stay','Ask about a stay'))}${cards([['HOTELS','A comfortable base','Ask about room configuration, meal plans, transport access and accessibility.'],['HOMESTAYS','Closer to local life','Confirm host arrangements, bathroom type, food preferences and quiet hours.'],['HOSTELS','A more social stay','Check dorm or private-room options, locker facilities, house rules and age restrictions.']])}<p class="small-copy">These stay types describe options to discuss, not existing partner properties. No unverified property names, ratings or room availability are displayed.</p></section>`;
 const draw=()=>{const type=main.querySelector('#stay-type').value,q=main.querySelector('#stay-search').value.toLowerCase();const matches=partnerStays.filter(p=>p.verified&&(type==='All stays'||p.type===type)&&`${p.name} ${p.destination}`.toLowerCase().includes(q));main.querySelector('#stay-count').textContent=`${matches.length} confirmed partner ${matches.length===1?'stay':'stays'}`;main.querySelector('#stay-results').innerHTML=matches.map(p=>`<article class="company-card"><span class="eyebrow green">${esc(p.type)} / ${esc(p.destination)}</span><h2>${esc(p.name)}</h2><p>${esc(p.description)}</p>${contact('stay','Enquire about this stay',p.name)}</article>`).join('')||'<div class="company-empty"><h3>Confirmed listings will appear here.</h3><p>No partner stays currently match this selection. Send your preferences, or explore partnership opportunities if you operate a property.</p><a class="underlined" href="#/partnerships">Become a stay partner ↗</a></div>';};main.querySelector('#stay-type').onchange=draw;main.querySelector('#stay-search').oninput=draw;draw();return;
 }
 if(route==='camping'){
 main.innerHTML=hero('CAMPING / TREKKING / EQUIPMENT','Pack thoughtfully.<br><em>Step outside.</em>','Build a practical equipment checklist and ask about route-specific kit arrangements. These are planning guides, not confirmed rental inventory.')+`<section class="wrap section top-tight"><div class="company-grid kit-grid">${campingKits.map(k=>`<article class="company-card kit-card"><span class="eyebrow green">${k.tag}</span><h2>${k.name}</h2><p>${k.description}</p><fieldset><legend>My packing checklist</legend>${k.items.map(item=>`<label class="kit-item"><input type="checkbox"> <span>${item}</span></label>`).join('')}</fieldset>${contact('equipment','Ask about this kit',k.name)}</article>`).join('')}</div><p class="small-copy">Checklist marks last for this visit only. Rental availability, deposit, fit, temperature rating, cleaning, damage terms and final cost must be confirmed before payment.</p><div class="company-process"><h2>Know the route.<br><em>Then choose the kit.</em></h2><ol><li>Confirm permitted camping locations and local restrictions.</li><li>Check weather, altitude and expected overnight temperatures.</li><li>Agree equipment responsibilities with your guide or operator.</li><li>Inspect equipment before departure and carry all waste back.</li></ol></div>${banner('Planning a particular route?','Include dates, group size, experience level and the equipment you already have.',contact('equipment','Discuss camping & trekking'))}</section>`;return;
 }
}
async function contactPage(main){
 const params=new URLSearchParams(location.hash.split('?')[1]||'');const hash=location.hash;let info={};try{info=await service('contact-info');}catch{}if(hash!==location.hash)return;
 const types={contact:'General travel enquiry',career:'Career interest',sponsor:'Sponsorship',partnership:'Partnership proposal',stay:'Accommodation enquiry',equipment:'Camping / trekking equipment'};
 main.innerHTML=hero('CONTACT / A HUMAN NEXT STEP','Tell us what<br><em>you have in mind.</em>','Trip ideas, partnerships or a question about KuboVistas — choose a topic and share the details that matter.')+`<section class="wrap section top-tight contact-layout"><aside class="company-card"><span class="eyebrow green">STAY CONNECTED</span><h2>Start a conversation.</h2>${info.email?`<p>Email: ${esc(info.email)}</p>`:''}${info.phone?`<p>Phone: ${esc(info.phone)}</p>`:''}${info.address?`<p>Address: ${esc(info.address)}</p>`:''}<a class="underlined" href="https://www.instagram.com/kubo_vista.official/" target="_blank" rel="noopener noreferrer">@kubo_vista.official ↗</a><p>For an existing trip, include your booking reference. Do not send passwords, card details, medical records or identity documents.</p><a href="#/grievance">Grievance information ↗</a><div class="social-links" data-social-links></div><p class="small-copy">This is not an emergency service. Contact local emergency services for urgent assistance.</p></aside><form class="account-form contact-form" id="contact-form"><label>Topic<select name="kind">${Object.entries(types).map(([id,label])=>`<option value="${id}" ${params.get('kind')===id?'selected':''}>${label}</option>`).join('')}</select></label><div class="form-grid"><label>Your name<input name="name" autocomplete="name" minlength="2" maxlength="120" required></label><label>Email<input type="email" name="email" autocomplete="email" maxlength="254" required></label></div><label>Organization / portfolio (optional)<input name="organization" maxlength="180"></label><label>Your message<textarea name="message" rows="7" minlength="20" maxlength="5000" required>${esc(params.get('subject')||'')}</textarea></label><label class="enquiry-trap" aria-hidden="true">Leave this field empty<input name="website" tabindex="-1" autocomplete="off"></label><label class="check-row"><input type="checkbox" name="consent" required>I agree that KuboVistas may use these details to review and respond to my enquiry. <a href="#/privacy">Privacy policy</a></label><button class="button" ${info.enquiries?'':'disabled'}>Send enquiry ↗</button><p class="form-status" role="status">${info.enquiries?'Your enquiry will be saved for the KuboVistas team.':'The enquiry form is not activated yet. Use the company Instagram link to get in touch.'}</p></form></section>`;
 mountSocialLinks(main);const transportHost=document.createElement('section');transportHost.className='wrap section top-tight';transportHost.innerHTML=transportLinks();main.append(transportHost);
 const form=main.querySelector('form');form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;const body=Object.fromEntries(new FormData(form));body.consent=body.consent==='on';try{const d=await service('enquiries',{method:'POST',body:JSON.stringify(body)});form.reset();form.querySelector('.form-status').textContent=`Enquiry saved. Your reference is ${d.reference}. This is not a booking or a confirmation of availability.`;}catch(e){form.querySelector('.form-status').textContent=e.message;}finally{button.disabled=!info.enquiries;}};
}
async function inbox(main){
 const hash=location.hash;let data;try{data=await service('enquiries');}catch(e){if(hash===location.hash)main.innerHTML=hero('TEAM ENQUIRIES','Authorized access<br><em>required.</em>',esc(e.message))+'<div class="wrap section"><a class="button" href="#/login">Sign in ↗</a></div>';return;}if(hash!==location.hash)return;
 main.innerHTML=hero('TEAM ENQUIRIES','Conversations<br><em>to follow up.</em>','The latest 100 enquiries. Reply through your verified business contact channel.')+`<section class="wrap section top-tight"><div class="company-grid">${data.enquiries.map(e=>`<article class="company-card"><span class="eyebrow green">${esc(e.kind)} / ${esc(e.status)}</span><h2>${esc(e.name)}</h2><p>${esc(e.email)}</p><p>${esc(e.organization)}</p><p>${esc(e.message)}</p><small>Reference ${esc(e.id)}</small>${e.status==='new'?`<button class="button small" data-review="${e.id}">Mark reviewed</button>`:''}</article>`).join('')||'<p>No enquiries yet.</p>'}</div><p id="inbox-status" role="status"></p></section>`;
 main.querySelectorAll('[data-review]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await service('enquiries',{method:'PATCH',body:JSON.stringify({id:b.dataset.review})});if(hash===location.hash)await inbox(main);}catch(e){main.querySelector('#inbox-status').textContent=e.message;b.disabled=false;}});
}
