export const destinations = [
 ['darjeeling','Darjeeling','North Bengal','Mountains','Tea trails & timeless hills','Wander through tea country, explore the town on foot, and leave room for a slow morning with a mountain view.',['Tea garden visits','Town walks','Himalayan viewpoints'],'3–4 days'],
 ['pelling','Pelling','Sikkim','Mountains','A different kind of high','Build a relaxed western Sikkim journey around mountain views, monastery visits and time in the surrounding countryside.',['Monastery visits','Mountain views','Local food'],'3–4 days'],
 ['goa','Goa','Goa','Coast','Follow the slower tide','Choose your own coastal rhythm: heritage lanes, long beach walks and unhurried meals. Pick a base before planning day trips.',['Beach walks','Heritage neighborhoods','Coastal food'],'4–6 days'],
 ['kalimpong','Kalimpong','North Bengal','Mountains','Between hills & horizons','A hill-town base for garden visits, local markets and quieter excursions into the surrounding countryside.',['Garden visits','Local markets','Hill viewpoints'],'2–3 days'],
 ['pabong','Pabong','North Bengal','Offbeat','The art of doing less','A small-village escape to shape around your host, countryside walks and meals with a view. Confirm the exact stay and approach road.',['Village walks','Homestay time','Local meals'],'2–3 days'],
 ['lebong','Lebong','North Bengal','Offbeat','A quieter side of the hills','Explore a quieter base around Darjeeling and build your days around local walks and nearby town visits.',['Slow walks','Hill scenery','Darjeeling excursions'],'2–3 days'],
 ['ramdhura','Ramdhura','North Bengal','Offbeat','Wake up above the everyday','Make space for early light, village walks and a relaxed homestay stay in the Kalimpong hills.',['Sunrise outings','Village walks','Homestays'],'2–3 days'],
 ['mirik','Mirik','North Bengal','Mountains','A lakeside state of mind','A gentle hill-town break with lakeside walks, tea-country excursions and plenty of time to pause.',['Lakeside walks','Tea country','Local markets'],'2–3 days'],
 ['lamahatta','Lamahatta','North Bengal','Forest','Take the scenic pause','Plan a forest-fringed retreat with short walks and a quiet base in the Darjeeling hills.',['Forest surroundings','Garden walks','Slow stays'],'1–2 days'],
 ['lepchajagat','Lepchajagat','North Bengal','Forest','Where the forest exhales','A forest escape for early mornings, birdwatching and time away from busy hill-town streets.',['Birdwatching','Forest walks','Mountain mornings'],'2–3 days'],
 ['chatakpur','Chatakpur','North Bengal','Forest','A little closer to the clouds','A village-and-forest escape best arranged with a local host. Check access conditions and any entry arrangements before departure.',['Village stays','Nature walks','Viewpoints'],'2–3 days'],
 ['samsu','Samsu','North Bengal','Offbeat','A place to find your own pace','An offbeat entry awaiting precise locality confirmation. Confirm the map pin and host before building a route.',['Host-led exploration','Local meals','Restful stays'],'2–3 days'],
 ['sittong','Sittong','North Bengal','Offbeat','Little villages, lasting memories','Explore village life and the surrounding countryside with a local host. Seasonal experiences depend on the time of your visit.',['Village walks','Local produce','Homestay meals'],'2–3 days'],
 ['bijanbari','Bijanbari','North Bengal','Offbeat','The valley takes its time','Use a valley base for countryside outings and an unhurried change of pace from Darjeeling.',['Valley scenery','Local markets','Countryside stays'],'2–3 days'],
 ['ahaldhara','Ahaldhara','North Bengal','Mountains','Meet the morning light','Plan a viewpoint-focused outing or quiet stay, with flexible timing for clouds and changing hill weather.',['Viewpoints','Tea-country scenery','Sunrise outings'],'1–2 days'],
 ['kolbong','Kolbong','North Bengal','Offbeat','A detour worth discovering','Confirm the exact locality and accommodation with your host before arranging transfers or nearby activities.',['Local exploration','Host-led walks','Slow travel'],'2–3 days'],
 ['kolakham','Kolakham','North Bengal','Forest','Find your forest rhythm','A quiet hill-village base for nature-led days. Confirm access, road conditions and local guiding arrangements.',['Birdwatching','Nature walks','Village stays'],'2–3 days'],
 ['peshok','Peshok','North Bengal','Offbeat','Take the tea-country road','A countryside escape built around hill scenery, local hospitality and short excursions.',['Tea-country scenery','Local meals','Scenic drives'],'2–3 days'],
 ['rishikhola','Rishikhola','North Bengal','Riverside','Let the river set the pace','Plan a riverside stay with time to unwind. Check current water and weather conditions; river access is never assumed safe.',['Riverside stays','Nature watching','Quiet mornings'],'2–3 days'],
 ['arunachal-pradesh','Arunachal Pradesh','Arunachal','Mountains','Go a little further','Choose one travel circuit and allow generous transfer time. Permits, road access and local arrangements need checking before departure.',['Cultural encounters','Mountain circuits','Local food'],'7–10 days'],
 ['bakkhali','Bakkhali','Coastal Bengal','Coast','A weekend by the water','Plan a coastal Bengal break with leisurely shoreline walks and simple local food. Check tide and weather advice locally.',['Shoreline walks','Coastal food','Weekend escapes'],'2–3 days'],
 ['henry-island','Henry Island','Coastal Bengal','Coast','Beyond the busy shoreline','Combine a coastal outing with time around Bakkhali. Confirm entry arrangements and accessible areas locally.',['Coastal scenery','Nature watching','Photography'],'1–2 days'],
 ['belpahari','Belpahari','Western Bengal','Forest','A different shade of Bengal','A countryside journey through western Bengal, with outings planned around local access and seasonal conditions.',['Countryside drives','Nature outings','Local culture'],'2–3 days'],
 ['north-sikkim','North Sikkim','Sikkim','Mountains','Into the high country','An itinerary-led region where access, permits and altitude shape the journey. Keep spare time for changing conditions.',['Mountain valleys','Local hospitality','Scenic circuits'],'4–6 days'],
 ['south-sikkim','South Sikkim','Sikkim','Mountains','A gentler mountain journey','Explore southern Sikkim at a slower pace, combining cultural stops, town visits and hill scenery.',['Cultural sites','Town walks','Hill scenery'],'3–4 days'],
 ['east-sikkim','East Sikkim','Sikkim','Mountains','A gateway to new perspectives','Start with a comfortable base and choose day trips around access, weather and the time you have.',['Gangtok outings','Local markets','Cultural visits'],'3–5 days'],
 ['west-sikkim','West Sikkim','Sikkim','Mountains','Wander into the quieter west','Build a journey around Pelling and nearby cultural or countryside stops, leaving space for long transfers.',['Monastery visits','Countryside stays','Mountain scenery'],'4–5 days'],
 ['kurseong','Kurseong','North Bengal','Mountains','Tea, mist & a slower morning','A hill-town pause for tea-country exploration, local walks and a gentler travel schedule.',['Tea-country visits','Town walks','Hill scenery'],'2–3 days']
].map(([id,name,region,type,tagline,description,highlights,duration])=>({id,name,region,type,tagline,description,highlights,duration}));

export const journeys = [
 {id:'tea-and-trails',name:'Tea, mist & mountain mornings',region:'North Bengal',days:5,stops:['darjeeling','lamahatta','kalimpong'],type:'The hill-country edit',description:'Town walks, tea-country detours and a quieter final night.',schedule:['Arrive and settle into Darjeeling. Keep the evening free.','Explore tea country and the town with a flexible local plan.','Travel toward Lamahatta and pause for a gentle nature outing.','Continue to Kalimpong for markets and local food.','Enjoy a slow breakfast before your onward transfer.']},
 {id:'sikkim-slowly',name:'Sikkim, one slow day at a time',region:'Sikkim',days:6,stops:['east-sikkim','south-sikkim','pelling'],type:'The Himalayan edit',description:'Cultural encounters, mountain views and room to breathe.',schedule:['Arrive at your eastern Sikkim base and rest.','Explore local markets and cultural stops.','Transfer toward southern Sikkim, allowing a full travel day.','Choose a relaxed local outing with your host.','Continue to Pelling and settle in.','A final mountain morning and onward transfer.']},
 {id:'coast-unhurried',name:'Salt in the air. Nothing on the clock.',region:'Goa',days:5,stops:['goa'],type:'The coastal edit',description:'Beach mornings, heritage lanes and long, unhurried lunches.',schedule:['Arrive in Goa and settle into your chosen coastal base.','Take a beach walk and explore nearby food spots.','Arrange a heritage outing with a local guide.','Keep the day open for your own coastal discoveries.','One last relaxed breakfast before departure.']}
];

export const notes = [
 {id:'slow-travel',category:'TRAVEL WELL',title:'The best itinerary leaves a little room.',time:'3 min read',intro:'Your trip does not need to become a checklist.',body:['Choose fewer bases. Every change of accommodation takes time from the place you came to experience.','Keep arrival days light and leave space between longer transfers. Ask your driver or host about realistic travel times for your actual dates.','Pick one anchor experience each day and let the rest stay flexible. Weather, a local recommendation or a good conversation can change the plan for the better.']},
 {id:'mountain-packing',category:'BEFORE YOU GO',title:'Pack lighter. Prepare a little better.',time:'4 min read',intro:'Practical essentials for a flexible hill-country trip.',body:['Start with layers, a waterproof outer layer, comfortable footwear and a reusable bottle. Ask your host about heating, hot water and laundry before packing.','Save your itinerary and accommodation details offline. Carry a charged power bank and keep original travel documents secure.','For high-altitude routes, get appropriate medical advice before departure. Your itinerary should allow acclimatization and flexibility rather than treating every mountain trip the same.']},
 {id:'local-travel',category:'GO GENTLY',title:'Be a guest, wherever you go.',time:'3 min read',intro:'Small choices make travel better for the places we visit.',body:['Ask before photographing people, private homes or ceremonies. Follow local guidance at religious and cultural sites.','Choose local guides and locally run stays where appropriate. Ask what is included and agree on prices before a service starts.','Carry your litter back, respect quiet hours and avoid disturbing wildlife. Stay on permitted paths and follow current access restrictions.']}
];
