export const destinations = [
 ['darjeeling','Darjeeling','North Bengal','Mountains','Tea trails & timeless hills','Wander through tea country, explore the town on foot, and leave room for a slow morning with a mountain view.',['Tea garden visits','Town walks','Himalayan viewpoints'],'3–4 days'],
 ['pelling','Pelling','Sikkim','Mountains','A different kind of high','Build a relaxed western Sikkim journey around mountain views, monastery visits and time in the surrounding countryside.',['Monastery visits','Mountain views','Local food'],'3–4 days'],
 ['goa','Goa','Goa','Coast','Follow the slower tide','Choose your own coastal rhythm: heritage lanes, long beach walks and unhurried meals. Pick a base before planning day trips.',['Beach walks','Heritage neighborhoods','Coastal food'],'4–6 days'],
 ['kalimpong','Kalimpong','North Bengal','Mountains','Between hills & horizons','A hill-town base for garden visits, local markets and quieter excursions into the surrounding countryside.',['Garden visits','Local markets','Hill viewpoints'],'2–3 days'],
 ['pabong','Pabong','North Bengal','Offbeat','The art of doing less','A small-village escape to shape around your host, countryside walks and meals with a view. Confirm the exact stay and approach road.',['Village walks','Homestay time','Local meals'],'2–3 days'],
 ['lebong','Lebong','North Bengal','Offbeat','A quieter side of the hills','Explore a quieter base around Darjeeling and build your days around local walks and nearby town visits.',['Slow walks','Hill scenery','Darjeeling excursions'],'2–3 days'],
 ['ramdhura','Ramdhura','North Bengal','Offbeat','Wake up above the everyday','Make space for early light, village walks and a relaxed homestay stay in the Kalimpong hills.',['Sunrise outings','Village walks','Homestays'],'2–3 days'],
 ['mirik','Mirik','North Bengal','Mountains','A lakeside state of mind','A gentle hill-town break with lakeside walks, tea-country excursions and plenty of time to pause.',['Lakeside walks','Tea country','Local markets'],'2–3 days'],
 ['lamahatta','Lamahatta','North Bengal','Forest','Take the scenic pause','Plan a forest-fringed retreat with short walks and a quiet base in the Darjeeling hills.',['Forest surroundings','Garden walks','Slow stays'],'1–2 days'],
 ['lepchajagat','Lepchajagat','North Bengal','Forest','Where the forest exhales','A forest escape for early mornings, birdwatching and time away from busy hill-town streets.',['Birdwatching','Forest walks','Mountain mornings'],'2–3 days'],
 ['chatakpur','Chatakpur','North Bengal','Forest','A little closer to the clouds','A village-and-forest escape best arranged with a local host. Check access conditions and any entry arrangements before departure.',['Village stays','Nature walks','Viewpoints'],'2–3 days'],
 ['samsu','Samsu','North Bengal','Offbeat','A place to find your own pace','An offbeat entry awaiting precise locality confirmation. Confirm the map pin and host before building a route.',['Host-led exploration','Local meals','Restful stays'],'2–3 days'],
 ['sittong','Sittong','North Bengal','Offbeat','Little villages, lasting memories','Explore village life and the surrounding countryside with a local host. Seasonal experiences depend on the time of your visit.',['Village walks','Local produce','Homestay meals'],'2–3 days'],
 ['bijanbari','Bijanbari','North Bengal','Offbeat','The valley takes its time','Use a valley base for countryside outings and an unhurried change of pace from Darjeeling.',['Valley scenery','Local markets','Countryside stays'],'2–3 days'],
 ['ahaldhara','Ahaldhara','North Bengal','Mountains','Meet the morning light','Plan a viewpoint-focused outing or quiet stay, with flexible timing for clouds and changing hill weather.',['Viewpoints','Tea-country scenery','Sunrise outings'],'1–2 days'],
 ['kolbong','Kolbong','North Bengal','Offbeat','A detour worth discovering','Confirm the exact locality and accommodation with your host before arranging transfers or nearby activities.',['Local exploration','Host-led walks','Slow travel'],'2–3 days'],
 ['kolakham','Kolakham','North Bengal','Forest','Find your forest rhythm','A quiet hill-village base for nature-led days. Confirm access, road conditions and local guiding arrangements.',['Birdwatching','Nature walks','Village stays'],'2–3 days'],
 ['peshok','Peshok','North Bengal','Offbeat','Take the tea-country road','A countryside escape built around hill scenery, local hospitality and short excursions.',['Tea-country scenery','Local meals','Scenic drives'],'2–3 days'],
 ['rishikhola','Rishikhola','North Bengal','Riverside','Let the river set the pace','Plan a riverside stay with time to unwind. Check current water and weather conditions; river access is never assumed safe.',['Riverside stays','Nature watching','Quiet mornings'],'2–3 days'],
 ['arunachal-pradesh','Arunachal Pradesh','Arunachal','Mountains','Go a little further','Choose one travel circuit and allow generous transfer time. Permits, road access and local arrangements need checking before departure.',['Cultural encounters','Mountain circuits','Local food'],'7–10 days'],
 ['bakkhali','Bakkhali','Coastal Bengal','Coast','A weekend by the water','Plan a coastal Bengal break with leisurely shoreline walks and simple local food. Check tide and weather advice locally.',['Shoreline walks','Coastal food','Weekend escapes'],'2–3 days'],
 ['henry-island','Henry Island','Coastal Bengal','Coast','Beyond the busy shoreline','Combine a coastal outing with time around Bakkhali. Confirm entry arrangements and accessible areas locally.',['Coastal scenery','Nature watching','Photography'],'1–2 days'],
 ['belpahari','Belpahari','Western Bengal','Forest','A different shade of Bengal','A countryside journey through western Bengal, with outings planned around local access and seasonal conditions.',['Countryside drives','Nature outings','Local culture'],'2–3 days'],
 ['north-sikkim','North Sikkim','Sikkim','Mountains','Into the high country','An itinerary-led region where access, permits and altitude shape the journey. Keep spare time for changing conditions.',['Mountain valleys','Local hospitality','Scenic circuits'],'4–6 days'],
 ['south-sikkim','South Sikkim','Sikkim','Mountains','A gentler mountain journey','Explore southern Sikkim at a slower pace, combining cultural stops, town visits and hill scenery.',['Cultural sites','Town walks','Hill scenery'],'3–4 days'],
 ['east-sikkim','East Sikkim','Sikkim','Mountains','A gateway to new perspectives','Start with a comfortable base and choose day trips around access, weather and the time you have.',['Gangtok outings','Local markets','Cultural visits'],'3–5 days'],
 ['west-sikkim','West Sikkim','Sikkim','Mountains','Wander into the quieter west','Build a journey around Pelling and nearby cultural or countryside stops, leaving space for long transfers.',['Monastery visits','Countryside stays','Mountain scenery'],'4–5 days'],
 ['kurseong','Kurseong','North Bengal','Mountains','Tea, mist & a slower morning','A hill-town pause for tea-country exploration, local walks and a gentler travel schedule.',['Tea-country visits','Town walks','Hill scenery'],'2–3 days']
].map(([id,name,region,type,tagline,description,highlights,duration])=>({id,name,region,type,tagline,description,highlights,duration}));

export const journeys = [
 {id:'tea-and-trails',name:'Tea, mist & mountain mornings',region:'North Bengal',days:5,stops:['darjeeling','lamahatta','kalimpong'],type:'The hill-country edit',description:'Town walks, tea-country detours and a quieter final night.',schedule:['Arrive and settle into Darjeeling. Keep the evening free.','Explore tea country and the town with a flexible local plan.','Travel toward Lamahatta and pause for a gentle nature outing.','Continue to Kalimpong for markets and local food.','Enjoy a slow breakfast before your onward transfer.']},
 {id:'sikkim-slowly',name:'Sikkim, one slow day at a time',region:'Sikkim',days:6,stops:['east-sikkim','south-sikkim','pelling'],type:'The Himalayan edit',description:'Cultural encounters, mountain views and room to breathe.',schedule:['Arrive at your eastern Sikkim base and rest.','Explore local markets and cultural stops.','Transfer toward southern Sikkim, allowing a full travel day.','Choose a relaxed local outing with your host.','Continue to Pelling and settle in.','A final mountain morning and onward transfer.']},
 {id:'coast-unhurried',name:'Salt in the air. Nothing on the clock.',region:'Goa',days:5,stops:['goa'],type:'The coastal edit',description:'Beach mornings, heritage lanes and long, unhurried lunches.',schedule:['Arrive in Goa and settle into your chosen coastal base.','Take a beach walk and explore nearby food spots.','Arrange a heritage outing with a local guide.','Keep the day open for your own coastal discoveries.','One last relaxed breakfast before departure.']}
];

const editorialNotes = [
 {id:'slow-travel',category:'ITINERARY PLANNING',title:'How to Plan a Slow India Itinerary Without Rushing',intro:'A practical method for choosing fewer bases, planning realistic transfers and leaving useful flexibility in an India tour.',published:'2026-09-27',updated:'2026-09-27',sections:[
  {heading:'Begin with the reason for the trip',paragraphs:['Before collecting attractions, decide what you want the journey to feel like. A quiet mountain break needs a different rhythm from a family sightseeing holiday. Write down two priorities—perhaps tea-country walks and local food—and treat everything else as optional. This keeps the itinerary useful when time, energy or weather changes.','Choose a region before choosing individual stops. Combining nearby places normally gives you more time on the ground and fewer repeated packing days. A North Bengal trip can connect Darjeeling, Lamahatta and Kalimpong; a Sikkim trip should be built as a separate route whose access and permits are checked for the actual travel dates.']},
  {heading:'Count transfer days honestly',paragraphs:['Road distance is not the same as travel time, especially in hill regions. Ask the accommodation or driver for a current estimate, then keep a buffer for meal stops, traffic and changing road conditions. Avoid placing a paid activity immediately after a long arrival or transfer.','Use arrival day for checking in, eating and learning the neighborhood. The first full day can hold the experience you care about most. If the trip contains several bases, alternate transfer days with lighter local days instead of building a chain of early departures.']},
  {heading:'Plan one anchor, not ten obligations',paragraphs:['Give each day one anchor experience: a guided town walk, a tea visit, a monastery circuit or a long coastal morning. Add a nearby alternative that can be dropped without disappointment. This makes the plan easier for children, older travelers and anyone affected by motion, altitude or heat.','Keep at least one open half-day in a trip longer than four days. It can absorb a delay, repeat a favorite place or follow a local recommendation. Flexibility is not wasted time; it is what prevents one disrupted booking from affecting the rest of the journey.']},
  {heading:'Confirm the changeable details',paragraphs:['A week before departure, reconfirm accommodation, pickup point, driver contact, activity timing and the documents required for each traveler. Check official weather and tourism notices instead of relying only on an old itinerary screenshot or social-media post.','Save confirmations, addresses and emergency contacts offline. Share the route with someone you trust and keep a small contingency amount outside the main wallet. A good itinerary is clear enough to follow and loose enough to recover when the road changes.']}
 ],sources:[{label:'India Meteorological Department',href:'https://mausam.imd.gov.in/'},{label:'Incredible India traveler information',href:'https://www.incredibleindia.gov.in/'}]},
 {id:'mountain-packing',category:'PACKING GUIDE',title:'Mountain Packing List for Sikkim and North Bengal',intro:'A layered, practical packing guide for hill towns, village stays and changing weather in the Eastern Himalayas.',published:'2026-09-27',updated:'2026-09-27',sections:[
  {heading:'Pack for change, not one forecast',paragraphs:['Hill weather can feel different across morning, afternoon and evening, so build a small layering system. Start with breathable everyday clothes, add a warm mid-layer and carry a waterproof outer layer. The aim is to adjust without filling the bag with several heavy jackets.','Take comfortable, already-worn footwear with dependable grip. A second light pair helps when the first gets wet. Include quick-drying socks, a compact umbrella or rain shell, sun protection and a reusable water bottle. Ask your stay whether towels, toiletries, heating and laundry are available.']},
  {heading:'Create a small day bag',paragraphs:['Keep water, prescribed medicine, tissues, a snack, sun protection, a light layer and a power bank together. Add a sealable pouch for litter and wet items. The day bag should be light enough to carry during walks without leaving essential medicine in the vehicle.','If you use glasses, hearing aids, inhalers or other personal equipment, carry a backup where practical. Do not separate critical medicine from your cabin bag during flights or long transfers. Keep prescriptions and basic medical information accessible to a travel companion.']},
  {heading:'Prepare documents and power',paragraphs:['Carry the original identity documents required for your route and keep secure digital copies. Permit requirements vary by destination, nationality and current rules; check the official tourism authority instead of copying another traveler’s document list.','Download tickets, accommodation contacts and the itinerary for offline use. A charged power bank and suitable charging cables are more useful than several gadgets. Mobile coverage can vary, so agree on meeting points and pickup details before leaving a connected area.']},
  {heading:'Treat altitude as a health question',paragraphs:['Not every hill trip is a high-altitude trip. If your route reaches higher areas, ask a qualified medical professional about your health, medicines and acclimatization needs. Do not use a generic online packing list as medical advice.','Plan gradual days, hydrate normally and tell your guide or companion if you feel unwell. Severe or worsening symptoms require prompt professional help and may require descending. The safest packing decision is a realistic itinerary supported by current local and medical guidance.']}
 ],sources:[{label:'Sikkim Tourism',href:'https://www.sikkimtourism.gov.in/'},{label:'India Meteorological Department',href:'https://mausam.imd.gov.in/'}]},
 {id:'local-travel',category:'RESPONSIBLE TRAVEL',title:'Responsible Travel in India: A Practical Guest Guide',intro:'Simple ways to support local hosts, respect communities and reduce avoidable impact while travelling in India.',published:'2026-09-27',updated:'2026-09-27',sections:[
  {heading:'Remember that a destination is also a home',paragraphs:['A viewpoint, village lane or market may be part of someone’s ordinary day. Ask before photographing people, homes, children, ceremonies or work. A friendly conversation does not automatically mean permission to record or post it online.','Follow dress, footwear, silence and photography guidance at religious and cultural places. If you are unsure, ask a host or guide quietly. Avoid blocking paths for photographs and never enter private land because a location was tagged publicly.']},
  {heading:'Spend with clarity and respect',paragraphs:['Locally run stays, guides, food businesses and crafts can keep more travel income near the destination. Choose them when they suit your needs, but still ask clear questions about registration, safety, inclusions and cancellation terms. Responsible travel does not mean skipping normal checks.','Agree on prices and scope before a service begins. Bargaining aggressively over a small amount can undermine the people whose knowledge makes the experience possible. At the same time, request written prices for larger bookings and never accept pressure to pay without understanding the terms.']},
  {heading:'Reduce what you leave behind',paragraphs:['Carry a refillable bottle where safe refilling is available, refuse unnecessary single-use items and take non-biodegradable litter back to a proper disposal point. A remote location is not improved by hiding waste behind rocks or leaving it beside an overflowing bin.','Stay on permitted paths, keep noise low and never feed or approach wildlife for a photograph. Follow fire restrictions and local instructions around forests, rivers and coastlines. Natural areas can be dangerous as well as fragile, so responsible behavior also protects the traveler.']},
  {heading:'Share carefully after the trip',paragraphs:['Credit guides, hosts or creators only with permission and describe experiences honestly. Avoid publishing private phone numbers, exact locations of sensitive sites or images that portray local people as scenery.','If a business handled a problem well, include that context in a review. If the concern involves safety or misconduct, preserve evidence and report it through the appropriate channel. Useful travel writing helps the next visitor make a better decision without exploiting the place being described.']}
 ],sources:[{label:'Incredible India',href:'https://www.incredibleindia.gov.in/'},{label:'Sikkim Tourism responsible travel information',href:'https://www.sikkimtourism.gov.in/'}]},
 {id:'darjeeling-trip-planning',category:'DESTINATION GUIDE',title:'Darjeeling Trip Planning Guide for 3–4 Days',intro:'How to shape a realistic first Darjeeling visit around arrival time, town walks, tea country and flexible mountain views.',published:'2026-09-27',updated:'2026-09-27',sections:[
  {heading:'Choose a comfortable arrival plan',paragraphs:['Treat the journey into the hills as part of the first day rather than squeezing a full sightseeing list after it. Confirm the pickup location, vehicle type and current travel estimate with your stay or operator. Eat before a long road transfer if needed and keep essential medicine in your day bag.','After check-in, learn the immediate neighborhood on foot if conditions and your energy allow. A simple meal and an early night can be more valuable than chasing several closing times. This gives the next morning room for the activity you care about most.']},
  {heading:'Build two town days with different rhythms',paragraphs:['Use one day for the central town, local food and a guided heritage or neighborhood walk. Group nearby stops rather than repeatedly crossing town. Ask before photographing people and confirm whether a religious or cultural site permits photography.','Use another day for tea-country scenery or a pre-arranged estate experience. Confirm visitor access and timing directly because working estates are not generic public parks. Keep a flexible alternative in town if rain, cloud or operational changes affect the plan.']},
  {heading:'Treat mountain views as a possibility',paragraphs:['A viewpoint can be memorable, but visibility depends on weather and season. Do not let a single sunrise plan determine whether the trip feels successful. If you choose an early outing, confirm departure time, warm clothing and transport the previous evening.','Leave space for an unplanned café stop, market visit or slower walk. Darjeeling works well when the itinerary includes the town itself, not only a sequence of famous photographs. Families and older travelers may prefer fewer stops with easier access.']},
  {heading:'Plan the onward journey before checkout',paragraphs:['Reconfirm the driver, pickup point and onward ticket a day ahead. Keep extra time between the hill transfer and a train or flight, particularly when weather or traffic could affect the road. The right buffer depends on current conditions, so ask locally rather than relying on a fixed internet estimate.','For a fourth day, choose one nearby excursion or simply keep a slower town day. Adding another overnight base can be worthwhile, but only if the transfer supports the experience you want. More pins on a map do not automatically create a better Darjeeling tour.']}
 ],sources:[{label:'Darjeeling District tourism',href:'https://darjeeling.gov.in/tourism/'},{label:'GTA Tourism',href:'https://darjeelingkalimpongtourism.com/'},{label:'India Meteorological Department',href:'https://mausam.imd.gov.in/'}]},
 {id:'sikkim-trip-planning',category:'DESTINATION GUIDE',title:'How to Plan a Sikkim Trip: Routes, Permits and Pace',intro:'A first-step Sikkim planning guide covering regional focus, realistic road days, permits and changing access conditions.',published:'2026-09-27',updated:'2026-09-27',sections:[
  {heading:'Choose one regional focus first',paragraphs:['Sikkim is better planned as a set of regional journeys than as a list of distant attractions. Start by deciding whether your priority is an eastern base, a western circuit around Pelling, a gentler southern journey or a permit-dependent northern route. Then match the number of nights to the road time.','Trying to combine every region in a short holiday creates repeated transfers and little recovery time. A six-day plan can use one main base and one second region, with a spare half-day for weather or access changes. Ask for the itinerary in day-by-day form before paying.']},
  {heading:'Check permits for the exact travelers and route',paragraphs:['Permit rules depend on nationality, route and the areas included. Some protected or restricted areas require arrangements through eligible or registered travel businesses. Requirements can change, so use the official Sikkim Tourism permit information and confirm again close to departure.','Send identity documents only through a verified channel and ask why each document is needed, how it will be stored and when it will be deleted. A social-media message is not enough evidence that a permit has been issued. Keep copies of approved documents available during travel.']},
  {heading:'Make road days part of the itinerary',paragraphs:['Mountain roads make map distance a poor predictor of comfort. Avoid placing a major paid activity immediately after a long transfer. Build meal, rest and viewpoint stops only where stopping is permitted and safe.','Keep luggage manageable if the route changes vehicles or accommodations. Reconfirm road status, pickup time and the next stay before each transfer. If authorities or local operators advise against a route, use the alternate plan rather than pressuring a driver to continue.']},
  {heading:'Plan responsibly around weather and altitude',paragraphs:['Check official forecasts and local notices, but remember that forecasts are not guarantees. Higher routes may need more flexibility and may not suit every traveler. Discuss health concerns with a qualified professional before travel and never conceal symptoms to preserve an itinerary.','Choose registered accommodation and clearly identified operators. Keep emergency contacts offline, share the route with someone you trust and retain a contingency budget. A responsible Sikkim tour is designed to change safely when access, weather or wellbeing requires it.']}
 ],sources:[{label:'Sikkim Tourism',href:'https://www.sikkimtourism.gov.in/'},{label:'Sikkim protected-area permit information',href:'https://www.sikkimtourism.gov.in/pap'},{label:'India Meteorological Department',href:'https://mausam.imd.gov.in/'}]},
 {id:'choose-himalayan-homestay',category:'STAY GUIDE',title:'How to Choose a Himalayan Homestay Before You Book',intro:'Questions to ask about location, access, rooms, meals, heating, connectivity and cancellation before choosing a hill stay.',published:'2026-09-27',updated:'2026-09-27',sections:[
  {heading:'Verify the exact place',paragraphs:['Similar property names and broad destination labels can hide very different locations. Ask for the full address, a map pin and the nearest recognizable landmark. Confirm whether the final approach is suitable for the vehicle and travelers in your group.','Request recent, representative photographs of the room and bathroom category you will receive. Clarify stairs, walking distance from parking and accessibility needs before paying. A beautiful view cannot compensate for an approach that someone in the group cannot manage.']},
  {heading:'Ask what daily comfort really includes',paragraphs:['Confirm bed type, occupancy, attached or shared bathroom, hot-water schedule, heating arrangement and backup power. In a cold season, ask how the room is warmed and whether extra bedding is included. Never use an unsafe heating device in a closed room.','Ask which meals are available, when they are served and whether dietary needs can be accommodated. A homestay may offer a fixed local menu rather than restaurant-style ordering; knowing this in advance helps both guest and host prepare.']},
  {heading:'Understand connection and transport limits',paragraphs:['Ask which mobile networks usually work, whether Wi-Fi is available and whether outages are common. Download tickets and directions before arrival. If you need connectivity for work or health, choose a stay with a realistic backup instead of assuming every village has stable service.','Confirm who arranges pickup, the price, vehicle type and payment method. If the host recommends a driver, ask whether the driver is licensed and how changes are handled. Do not send a large transport payment to an unverified personal account.']},
  {heading:'Get the booking terms in writing',paragraphs:['The confirmation should state dates, guest count, room category, meals, total price, taxes or extra charges, advance paid and balance due. Ask what happens if weather or road restrictions affect arrival; do not assume every disruption produces a full refund.','Keep the host’s phone number, address and cancellation terms offline. Read independent recent reviews, but judge whether they discuss the same room and season. A strong homestay choice comes from clear expectations, not only a highly edited photograph.']}
 ],sources:[{label:'Sikkim Tourism accommodation and traveler information',href:'https://www.sikkimtourism.gov.in/'},{label:'Darjeeling District where to stay',href:'https://darjeeling.gov.in/where-to-stay/'}]},
 {id:'monsoon-hill-travel',category:'SEASONAL GUIDE',title:'Monsoon Hill Travel in India: A Practical Safety Checklist',intro:'A conservative checklist for forecasts, road changes, footwear, buffers and decisions during rainy-season hill travel.',published:'2026-09-27',updated:'2026-09-27',sections:[
  {heading:'Check conditions, not just climate averages',paragraphs:['A monthly weather chart cannot tell you the condition of a road on your departure day. Review official forecasts and warnings, then ask the accommodation or operator about the local approach. Recheck before each transfer because rain can affect nearby routes differently.','Do not treat a social post from last week as a live safety update. Follow instructions from district authorities, police and transport operators. If access is restricted, change the plan; a booking or short holiday is never a reason to cross a closure.']},
  {heading:'Build buffers into every connection',paragraphs:['Avoid a tight same-day connection between a hill transfer and the last train or flight. Keep a realistic buffer based on current local guidance, and consider a gateway-city night when missing the connection would create a major cost or safety problem.','Reserve flexible accommodation or tickets where the price difference is reasonable. Save provider contacts and cancellation terms offline. Travel insurance may help with some covered events, but read exclusions and claim requirements instead of assuming every weather disruption is included.']},
  {heading:'Pack to stay dry and visible',paragraphs:['Use a waterproof outer layer, quick-drying clothes and footwear with grip. Protect documents, medicine and electronics inside separate waterproof pouches. Carry a compact light and power bank in case a delay continues after dark.','Keep luggage small enough to move safely without blocking your view of steps or uneven ground. Change wet socks and clothes when possible, and do not place wet items beside heaters or open flames. Ask the stay where shoes and rain gear can dry.']},
  {heading:'Know when to stop',paragraphs:['Do not walk through moving water, stand below unstable slopes or stop a vehicle where falling material is visible. Rivers and waterfalls can change quickly after rain; view them only from permitted locations and follow local instructions.','Tell someone your route and expected arrival time. If the driver, guide or authority recommends turning back, accept the change. The best rainy-season itinerary has alternatives and enough time to wait safely rather than trying to defeat the weather.']}
 ],sources:[{label:'India Meteorological Department',href:'https://mausam.imd.gov.in/'},{label:'IMD district forecasts',href:'https://mausam.imd.gov.in/imd_latest/contents/agromet/advisory/indiadistrictforecast.php'}]},
 {id:'slow-goa-itinerary',category:'DESTINATION GUIDE',title:'Slow Goa Itinerary: How to Choose a Base and Set the Pace',intro:'A practical way to choose one Goa base, balance coast and heritage, and avoid losing the holiday to repeated transfers.',published:'2026-09-27',updated:'2026-09-27',sections:[
  {heading:'Choose the base before the attractions',paragraphs:['Start with the kind of day you want: walkable meals, quieter mornings, nightlife access, heritage exploration or a family-friendly stay. Then compare properties in a specific area. “Goa” is too broad a location for estimating daily travel from a hotel.','Check the exact map pin, distance to the places you care about and safe transport options for evening returns. A lower room price can disappear if every meal or activity requires a long paid ride.']},
  {heading:'Separate coast days from inland days',paragraphs:['Keep at least one day close to the chosen coast so the trip has time to breathe. Use another day for a planned heritage or cultural outing, grouping nearby places and respecting site guidance. Avoid crossing the state repeatedly for isolated photo stops.','If your interests are split between distant areas, consider two bases only when the trip is long enough to justify packing and checkout. For a short break, one well-chosen base and fewer day trips usually create a calmer itinerary.']},
  {heading:'Plan around heat, rain and water safety',paragraphs:['Use official weather information and follow beach safety flags, lifeguards and local restrictions. Do not enter rough water because another visitor is swimming. Conditions can change by location and time, and a sunny photograph is not a safety assessment.','Carry sun protection and water, and schedule outdoor activity for a comfortable part of the day. During rain, confirm whether roads and planned activities are operating. Keep a flexible indoor or food-focused alternative rather than forcing the original schedule.']},
  {heading:'Book services with clear terms',paragraphs:['Use registered accommodation and identifiable operators. For a taxi, rental or activity, confirm the total charge, inclusions, license requirements, deposit and damage terms before accepting. Photograph an agreed rental condition only with the provider’s knowledge.','Save the booking confirmation and emergency contacts offline. Respect residential areas, local rules and waste systems. A slow Goa itinerary is not about doing nothing; it is about spending time on the experiences you chose instead of commuting between every popular pin.']}
 ],sources:[{label:'Department of Tourism, Government of Goa',href:'https://www.goa.gov.in/department/tourism/'},{label:'Goa Tourism Development Corporation',href:'https://goa-tourism.com/'},{label:'India Meteorological Department',href:'https://mausam.imd.gov.in/'}]}
];

const articleWords = note => note.sections.flatMap(section => section.paragraphs).join(' ').trim().split(/\s+/).length;
export const notes = editorialNotes.map(note => ({
 ...note,
 body: note.sections.flatMap(section => section.paragraphs),
 wordCount: articleWords(note),
 time: `${Math.max(3,Math.ceil(articleWords(note)/200))} min read`
}));
