import { destinations } from './data.js';
import { metadata, seasonalStatus, monthNames, indiaDate } from './destination-meta.js';
export const escapeText=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let map,group,mapElement,libraryPromise,mapSequence=0;
const colors={green:'#2b9563',yellow:'#dd9f17',red:'#cd4845'};
function loadMapLibrary(){if(window.L)return Promise.resolve(window.L);if(!libraryPromise)libraryPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='assets/leaflet.js';script.onload=()=>resolve(window.L);script.onerror=()=>{libraryPromise=null;script.remove();reject(Error('Map library could not load.'));};document.head.append(script);});return libraryPromise;}
export function disposeMap(){mapSequence++;if(map){map.remove();map=null;group=null;mapElement=null;}}
export function mapMarkup(){return `<section class="discovery-map"><div class="map-heading"><div><span class="eyebrow green">INDIA / SEASONAL EXPLORER</span><h2>A place for<br><em>every season.</em></h2></div><label>Touring month<select id="touring-month">${monthNames.map((name,i)=>`<option value="${i+1}" ${i+1===Number(indiaDate().slice(5,7))?'selected':''}>${name}</option>`).join('')}</select></label></div><div class="map-legend"><span><i class="season-dot green"></i>Green · Generally favorable</span><span><i class="season-dot yellow"></i>Yellow · Mixed / review locally</span><span><i class="season-dot red"></i>Red · Higher seasonal caution</span></div><p class="small-copy">Seasonal planning estimates, not live safety ratings or weather forecasts. Red does not mean a destination is closed. “Crowded” and “famous” are editorial categories, not live visitor counts.</p><div class="map-layout"><div><div id="india-map" aria-label="Interactive destination map of India"></div><p id="map-status" role="status">Loading map…</p><div class="map-controls"><button class="text-button" id="map-india">India view ↗</button><button class="text-button" id="map-results">Zoom to results ↗</button></div></div><div class="map-destination-list" id="map-destination-list" aria-label="Destinations on the map"></div></div><p class="small-copy">Dots show approximate town or regional centers. Samsu and Kolbong use labeled area references pending exact locality confirmation. Overlapping dots separate as you zoom; use the list to select any destination. New destinations appear automatically when coordinates are added.</p><p class="small-copy">Map tiles: <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap contributors</a>. Check current local guidance with <a href="https://mausam.imd.gov.in/" target="_blank" rel="noopener noreferrer">IMD</a> and relevant tourism authorities before travel.</p></section>`;}
export async function updateDestinationMap(destinations,month){
 const version=++mapSequence;const element=document.querySelector('#india-map');if(!element)return;
 const list=document.querySelector('#map-destination-list');
 const mapped=destinations.filter(d=>Number.isFinite(metadata(d).lat)&&Number.isFinite(metadata(d).lng));
 list.innerHTML=destinations.map(d=>{const s=seasonalStatus(d,month),p=metadata(d);return `<div class="map-place"><button data-map-place="${escapeText(d.id)}"><i class="season-dot ${s.color}"></i><span><strong>${escapeText(d.name)}</strong><small>${s.label}${p.unconfirmed?' · area only':''}</small></span></button><a href="#/destination/${escapeText(d.id)}" aria-label="Open ${escapeText(d.name)} guide">↗</a></div>`;}).join('')||'<p>No destinations match your filters.</p>';
 try{const L=await loadMapLibrary();if(!element.isConnected||version!==mapSequence)return;
 if(mapElement!==element){if(map)map.remove();mapElement=element;map=L.map(element,{scrollWheelZoom:false,zoomControl:true}).setView([22.5,81.5],4);group=L.layerGroup().addTo(map);const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);tiles.on('tileerror',()=>{const label=document.querySelector('#map-status');if(label)label.textContent='Map tiles are unavailable. Destination dots and the list remain usable.';});}
 group.clearLayers();const markers=new Map();mapped.forEach(d=>{const p=metadata(d),s=seasonalStatus(d,month);const marker=L.marker([p.lat,p.lng],{title:`${d.name}: ${s.label}`,icon:L.divIcon({className:'destination-map-icon',html:`<span style="background:${colors[s.color]}"></span>`,iconSize:[20,20],iconAnchor:[10,10]})}).addTo(group);marker.bindPopup(`<strong>${escapeText(d.name)}</strong><p>${s.label} · ${monthNames[month-1]}</p><p>${s.reason}</p><small>${escapeText(p.anchor||'Approximate locality center')}</small><p><a href="#/destination/${escapeText(d.id)}">Open destination guide ↗</a></p>`);markers.set(d.id,marker);});
 document.querySelector('#map-status').textContent=`${mapped.length} of ${destinations.length} filtered places on the map. ${monthNames[month-1]} seasonal guidance.`;
 list.querySelectorAll('[data-map-place]').forEach(button=>button.onclick=()=>{const marker=markers.get(button.dataset.mapPlace);if(marker){map.setView(marker.getLatLng(),11,{animate:!matchMedia('(prefers-reduced-motion: reduce)').matches});marker.openPopup();}else document.querySelector('#map-status').textContent='Coordinates for this destination are pending.';});
 document.querySelector('#map-india').onclick=()=>map.setView([22.5,81.5],4);
 document.querySelector('#map-results').onclick=()=>{if(mapped.length)map.fitBounds(mapped.map(d=>[metadata(d).lat,metadata(d).lng]),{padding:[30,30],maxZoom:11});};
 map.invalidateSize();
 }catch{if(element.isConnected)document.querySelector('#map-status').textContent='The interactive map is unavailable. Use the destination list and guide links.';}
}
const weatherCode=code=>typeof code!=='number'?'Conditions unavailable':code===0?'Clear':code<=3?'Partly cloudy / overcast':[45,48].includes(code)?'Fog':[51,53,55,56,57].includes(code)?'Drizzle':[61,63,65,66,67,80,81,82].includes(code)?'Rain':[71,73,75,77,85,86].includes(code)?'Snow':code>=95?'Thunderstorms':'Conditions unavailable';
const value=(n,unit='')=>typeof n==='number'&&Number.isFinite(n)?`${Math.round(n)}${unit}`:'Unavailable';
export function mountWeather(container,destination,date=''){
 if(!container)return;
 container.innerHTML=`<section class="weather-panel"><span class="eyebrow green">WEATHER / YOUR TRAVEL DATES</span><h3>Before you set out.</h3><p>Current modeled conditions and a day forecast for your selected destination.</p><form class="weather-form"><label>Travel day<input type="date" name="weatherDate" value="${escapeText(date?.slice(0,10)||indiaDate())}" required></label><button class="button small">Check weather ↗</button></form><p class="weather-season"></p><div class="weather-results" role="status"><p>Choose your travel day to check available weather.</p></div><p class="small-copy">Forecasts are estimates, not guarantees. High-altitude routes and nearby valleys can differ substantially. <a href="https://mausam.imd.gov.in/" target="_blank" rel="noopener noreferrer">Check IMD alerts ↗</a></p></section>`;
 const form=container.querySelector('form'),results=container.querySelector('.weather-results');let sequence=0;
 const showSeason=()=>{const d=destinations.find(d=>d.id===destination);const month=Number(form.elements.weatherDate.value.slice(5,7));if(d&&month){const season=seasonalStatus(d,month);container.querySelector('.weather-season').innerHTML=`<i class="season-dot ${season.color}"></i> ${monthNames[month-1]}: ${season.label}. ${season.reason}`;}};form.elements.weatherDate.onchange=showSeason;showSeason();
 const load=async()=>{showSeason();const version=++sequence;form.querySelector('button').disabled=true;results.textContent='Checking weather…';try{const r=await fetch(`/api/config?service=weather&destination=${encodeURIComponent(destination)}&date=${encodeURIComponent(form.elements.weatherDate.value)}`);const d=await r.json();if(!r.ok)throw Error(d.error||'Weather unavailable');if(version!==sequence||!container.isConnected)return;const c=d.current,f=d.daily;results.innerHTML=`<div class="weather-grid"><article><span>CURRENT MODEL ESTIMATE</span><strong>${value(c.temperature_2m,'°C')}</strong><p>${weatherCode(c.weather_code)}</p><small>Feels ${value(c.apparent_temperature,'°C')} · Humidity ${value(c.relative_humidity_2m,'%')} · Wind ${value(c.wind_speed_10m,' km/h')}</small><small>Model time ${escapeText(c.time)} IST</small></article><article><span>${escapeText(d.selectedDate)} / DAY FORECAST</span>${f?`<strong>${value(f.temperature_2m_min,'°')} – ${value(f.temperature_2m_max,'°C')}</strong><p>${weatherCode(f.weather_code)}</p><small>Rain chance ${value(f.precipitation_probability_max,'%')} · Rain ${value(f.precipitation_sum,' mm')} · Max wind ${value(f.wind_speed_10m_max,' km/h')}</small>`:'<h4>Forecast not available yet</h4>'}</article></div><p>${escapeText(d.notice)}</p><p class="small-copy">${escapeText(d.reference)}. Retrieved ${escapeText(new Date(d.fetchedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}))} IST. <a href="https://open-meteo.com/" target="_blank" rel="noopener noreferrer">Weather data by Open-Meteo</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">CC BY 4.0</a>.</p>`;}catch(error){if(version===sequence&&container.isConnected)results.textContent=error.message;}finally{if(version===sequence)form.querySelector('button').disabled=false;}};
 form.onsubmit=event=>{event.preventDefault();load();};load();
}
