import { notes } from './data.js';
import { getAccountSession } from './account.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const profile='https://www.instagram.com/kubo_vista.official/';
async function api(path='',options={}){const r=await fetch('/api/journal'+path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json'}});const d=await r.json();if(!r.ok)throw Error(d.error||'Journal is unavailable.');return d;}
function embed(url,title){return `<div class="instagram-slot" data-url="${esc(url)}"><span class="eyebrow">INSTAGRAM / KuboVistas</span><h3>${esc(title)}</h3><p>Loading this preview connects to Instagram, which may use cookies. You can also open it directly.</p><button class="button" data-load-instagram>Load Instagram preview</button><a class="underlined" href="${esc(url)}" target="_blank" rel="noopener noreferrer">Open on Instagram ↗</a><div class="instagram-frame"></div></div>`;}
function wireEmbeds(main){main.querySelectorAll('[data-load-instagram]').forEach(button=>button.onclick=()=>{const slot=button.closest('.instagram-slot');const holder=slot.querySelector('.instagram-frame');if(holder.firstChild){holder.replaceChildren();button.textContent='Load Instagram preview';return;}const frame=document.createElement('iframe');frame.src=slot.dataset.url+'embed/';frame.title=slot.querySelector('h3').textContent;frame.loading='lazy';frame.referrerPolicy='strict-origin-when-cross-origin';frame.allow='encrypted-media; fullscreen';holder.replaceChildren(frame);button.textContent='Hide Instagram preview';});}
const intro=(tag,title,copy)=>`<section class="wrap journal-intro"><span class="eyebrow">${tag}</span><h1>${title}</h1><p>${copy}</p></section>`;
const card=p=>`<a class="journal-card" href="${p.local?'#/guide/':'#/story/'}${esc(p.id)}"><span class="eyebrow">${p.kind==='company'?'KuboVistas JOURNAL':'TRAVELER STORY'}</span><h2>${esc(p.title)}</h2><p>${esc(p.summary)}</p><div class="journal-byline"><span>${esc(p.kind==='company'?'KuboVistas editorial':p.author_name)}</span><span>Read story ↗</span></div></a>`;
export async function renderJournal(route,id,main){
 const hash=location.hash;const active=()=>location.hash===hash;
 if(route==='write'||route==='my-stories'||route==='journal-review')return authorPage(route,main,active);
 if(route==='story'){
  const {posts}=await api('?id='+encodeURIComponent(id||''));if(!active())return;
  const p=posts[0];main.innerHTML=p?intro(p.kind==='company'?'KuboVistas JOURNAL':'TRAVELER STORY',esc(p.title),esc(p.summary))+`<article class="wrap journal-reading"><p class="article-meta">By ${esc(p.kind==='company'?'KuboVistas editorial':p.author_name)} · ${new Date(p.published_at).toLocaleDateString('en-IN')}</p>${p.body.split(/\n\s*\n/).map(t=>`<p>${esc(t)}</p>`).join('')}${p.instagram_url?embed(p.instagram_url,p.title):''}<a class="button" href="#/journal">Back to journal ↗</a></article>`:intro('JOURNAL','Story not found.','This story may not be published yet. <a href="#/journal">Back to journal</a>');wireEmbeds(main);return;
 }
 let remote={posts:[]},failure='';try{remote=await api();}catch{failure='Traveler stories are temporarily unavailable. Company field notes are still here.';}if(!active())return;
 const company=notes.map(n=>({id:n.id,title:n.title,summary:n.intro,author_name:'KuboVistas editorial',kind:'company',local:true}));
 const posts=[...remote.posts.filter(p=>p.kind!=='instagram'),...company];
 main.innerHTML=intro('THE KuboVistas JOURNAL','Good places.<br><em>Even better stories.</em>','Field notes from our team. First-hand journeys from our travelers. Little moments from the road.')+`<section class="wrap journal-actions"><a class="button" href="#/write">Share your story ↗</a><a class="underlined" href="#/my-stories">My submissions</a><a class="underlined" href="#/journal-review">Editorial desk</a></section><section class="wrap section top-tight"><div class="journal-toolbar"><div role="group" aria-label="Story source"><button class="active" data-source="all" aria-pressed="true">All stories</button><button data-source="company" aria-pressed="false">Company blogs</button><button data-source="traveler" aria-pressed="false">Traveler blogs</button></div><label>Find a story<input type="search" id="journal-search" placeholder="Search titles, authors, places…"></label></div><p id="journal-status" role="status">${failure}</p><div class="journal-grid" id="journal-results"></div></section><section class="wrap section journal-social"><div><span class="eyebrow">MOMENTS BETWEEN DESTINATIONS</span><h2>From our<br><em>Instagram diary.</em></h2><p>Reels, photographs and everyday moments from @kubo_vista.official.</p><a class="underlined" href="${profile}" target="_blank" rel="noopener noreferrer">Follow KuboVistas ↗</a><p class="journal-caption">Previews depend on Instagram availability and the account’s embedding settings. Direct links remain available.</p></div><div class="instagram-grid">${embed(profile,'@kubo_vista.official')}${remote.posts.filter(p=>p.kind==='instagram').map(p=>embed(p.instagram_url,p.title)).join('')}</div></section>`;
 let source='all';const search=main.querySelector('#journal-search');const draw=()=>{const term=search.value.toLowerCase().trim();const visible=posts.filter(p=>(source==='all'||p.kind===source)&&`${p.title} ${p.summary} ${p.author_name}`.toLowerCase().includes(term));main.querySelector('#journal-results').innerHTML=visible.length?visible.map(card).join(''):'<div class="journal-empty"><h2>No stories here yet.</h2><p>Try another search, or share a journey of your own.</p><a href="#/write">Write a traveler story ↗</a></div>';main.querySelector('#journal-status').textContent=failure||`${visible.length} ${visible.length===1?'story':'stories'}`;};main.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{source=b.dataset.source;main.querySelectorAll('[data-source]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});draw();});search.oninput=draw;draw();wireEmbeds(main);
}
async function authorPage(route,main,active){
 const session=await getAccountSession(true);if(!active())return;
 if(!session?.user){main.innerHTML=intro('YOUR JOURNEYS, IN WORDS','Every trip has<br><em>a story.</em>','Sign in to write and manage your stories. Traveler submissions are reviewed before publication.')+'<section class="wrap section top-tight"><a class="button" href="#/login?return=%2Fwrite">Sign in to continue ↗</a> <a class="underlined" href="#/journal">Read the journal</a></section>';return;}
 const data=await api(route==='journal-review'?'?review=1':'?mine=1');if(!active())return;
 if(route!=='write'){
 main.innerHTML=intro(route==='journal-review'?'EDITORIAL DESK':'YOUR NOTEBOOK',route==='journal-review'?'Stories awaiting<br><em>your review.</em>':'Your stories.<br><em>Your perspective.</em>','Only approved stories appear in the public journal.')+`<section class="wrap section top-tight"><a class="button" href="#/write">Write a story ↗</a> <a class="underlined" href="#/journal">Back to journal</a><div class="journal-submissions">${data.posts.length?data.posts.map(p=>`<article class="journal-submission"><span class="eyebrow">${esc(p.status)} · ${esc(p.kind)}</span><h2>${esc(p.title)}</h2><p>By ${esc(p.kind==='company'?'KuboVistas editorial':p.author_name)}</p><p>${esc(p.summary)}</p><details><summary>Read submission</summary><p class="story-text">${esc(p.body)}</p></details>${route==='journal-review'?`<div class="journal-actions"><button class="button" data-moderate="${p.id}" data-status="published">Approve & publish</button><button class="button secondary" data-moderate="${p.id}" data-status="rejected">Decline</button></div>`:''}</article>`).join(''):'<p>No submissions to display.</p>'}</div><p role="status" id="editor-status"></p></section>`;
 main.querySelectorAll('[data-moderate]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('',{method:'PATCH',body:JSON.stringify({id:b.dataset.moderate,status:b.dataset.status})});if(active())await authorPage(route,main,active);}catch(e){main.querySelector('#editor-status').textContent=e.message;b.disabled=false;}});return;
 }
 main.innerHTML=intro('CONTRIBUTE TO THE JOURNAL','A journey worth<br><em>putting into words.</em>','Share practical details and your own experiences. Your display name will appear publicly with an approved story.')+`<section class="wrap section top-tight"><form class="account-form journal-editor" id="story-form">${data.admin?'<label>Publication type<select name="kind"><option value="company">Company blog</option><option value="traveler">Traveler story</option><option value="instagram">Company Instagram feature</option></select></label><label>Instagram post or reel URL (for Instagram features only)<input name="instagram_url" type="url" placeholder="https://www.instagram.com/reel/…/"></label>':''}<label>Title<input name="title" minlength="5" maxlength="150" required></label><label>Short introduction<textarea name="summary" minlength="20" maxlength="350" required></textarea></label><label>Your story<textarea name="body" rows="14" minlength="80" maxlength="15000" required placeholder="Where did you go? What did you learn? Separate paragraphs with a blank line."></textarea></label><label class="check-row"><input type="checkbox" name="consent" required>I own this content or have permission to publish it. I agree to public publication with my name and will not include someone’s private details.${data.admin?' Instagram links must belong to KuboVistas.':''}</label><button class="button">${data.admin?'Publish':'Submit for review'} ↗</button><p class="form-status" role="status"></p></form></section>`;
 const form=main.querySelector('form');form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;const body=Object.fromEntries(new FormData(form));body.consent=body.consent==='on';try{await api('',{method:'POST',body:JSON.stringify(body)});if(active())location.hash='/my-stories';}catch(e){form.querySelector('.form-status').textContent=e.message;button.disabled=false;}};
}
