import { packages, packageById } from './packages.js';
import { destinations } from './data.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const stop=id=>destinations.find(item=>item.id===id)?.name||id;
const card=p=>`<article class="signature-card"><div class="signature-card-art"><span>${esc(p.region)}</span><strong>${String(p.days).padStart(2,'0')}<small>days</small></strong></div><div class="signature-card-body"><span class="eyebrow green">${esc(p.theme)}</span><h2>${esc(p.name)}</h2><p>${esc(p.intro)}</p><p class="signature-route">${p.stops.map(stop).map(esc).join(' → ')}</p><a class="button outline" href="/packages/${p.id}">View planning details ↗</a></div></article>`;
export function renderPackages(main,id){
 if(!id){document.title='Signature Packages — KuboVistas';main.innerHTML=`<section class="page-intro wrap"><span class="eyebrow green">SIGNATURE PACKAGE IDEAS</span><h1>Your journey,<br><em>thoughtfully shaped.</em></h1><p>Ten flexible starting points. Dates, stays, permits, inclusions and prices are confirmed only in your personal quotation.</p></section><section class="wrap section top-tight"><div class="signature-grid">${packages.map(card).join('')}</div><p class="signature-disclaimer">These are itinerary concepts, not confirmed departures, available inventory or fixed-price offers. No payment is taken from a package page.</p></section>`;return;}
 const p=packageById(id);if(!p){main.innerHTML='<section class="wrap page-intro"><h1>Package not found.</h1><a href="/packages">Explore all packages ↗</a></section>';return;}
 document.title=`${p.name} | KuboVistas Packages`;
 const steps=p.stops.map((place,index)=>`<li><span>STOP ${String(index+1).padStart(2,'0')}</span><div><h3>${esc(stop(place))}</h3><p>Discuss timing, preferred stays, transfer conditions and experiences with your travel expert.</p><a href="/destinations/${place}">Explore destination ↗</a></div></li>`).join('');
 const planner=`/planner?destination=${encodeURIComponent(p.stops[0])}&days=${p.days}`;
 main.innerHTML=`<section class="page-intro wrap signature-hero"><a class="back-link" href="/packages">← All packages</a><span class="eyebrow green">${esc(p.region)} · ${p.days} DAYS · ${esc(p.theme)}</span><h1>${esc(p.name)}</h1><p>${esc(p.intro)}</p><div class="signature-actions"><a class="button" href="${planner}">Request a personal quotation ↗</a><a class="button outline" href="/company/contact?kind=contact&subject=${encodeURIComponent(p.name)}">Talk to the travel team</a></div></section><section class="wrap section signature-detail"><article><span class="eyebrow green">YOUR ROUTE</span><h2>Room to follow your own pace.</h2><ol class="signature-stops">${steps}</ol></article><aside class="signature-sidebar"><h2>Before you decide</h2><dl><div><dt>Indicative duration</dt><dd>${p.days} days</dd></div><div><dt>Price</dt><dd>Personal quotation</dd></div><div><dt>Departure</dt><dd>By consultation</dd></div></dl><h3>Discuss in your quotation</h3><ul><li>Accommodation type and room category</li><li>Transfers and local experiences</li><li>Meals, applicable taxes and exclusions</li><li>Permit needs and accessible options</li><li>Cancellation policy and payment schedule</li></ul><p>No supplier or availability is reserved by viewing this page. The written quote controls inclusions, taxes, cancellation and payment terms.</p><a class="button" href="${planner}">Start a trip request ↗</a></aside></section>`;
}
