import { destinations } from './data.js';
import { getAccountSession } from './account.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const styles={solo:'Solo explorers',couples:'Couples',friends:'Friends & groups',family:'Families',students:'Students · 18+'};
const name=id=>destinations.find(d=>d.id===id)?.name||id;
const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v);
const options=(all=false)=>`${all?'<option value="">Every destination</option>':'<option value="">Choose a destination</option>'}${destinations.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('')}`;
const styleOptions=(all=false)=>`${all?'<option value="">Every travel style</option>':''}${Object.entries(styles).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}`;
async function api(view='',body,method='POST'){
 const r=await fetch('/api/travel-date'+(view?'?view='+view:''),{credentials:'same-origin',headers:{'Content-Type':'application/json'},...(body?{method,body:JSON.stringify(body)}:{})});
 const data=await r.json();if(!r.ok)throw Error(data.error||'Travel Date could not be reached.');return data;
}
export const travelTogetherSection=()=>`<section class="wrap td-invitation"><div><span class="eyebrow">MORE OF INDIA. MORE WAYS TO GO.</span><h2>Your people.<br><em>Your kind of journey.</em></h2><p>Travel solo, make memories as a couple, bring your family or gather your friends. We help students and school or college organisers shape thoughtful budget trips, too.</p><div class="td-tags"><span>Solo</span><span>Couples</span><span>Families</span><span>Groups</span><span>Student budgets</span></div><a class="button" href="#/travel-date">Discover Travel Date ↗</a> <a class="underlined" href="#/contact">Organise a school or college trip ↗</a></div><div class="td-invitation-art"><span class="eyebrow">TRAVEL DATE / KUBOVISTAS</span><strong>Different stories.<br>One shared<br><em>direction.</em></strong><p>Find people with a similar destination, travel window and budget. Get to know our country, together.</p></div></section>`;
const guidelines=`<details class="td-guidelines"><summary>Before you connect: companion guidelines</summary><ul><li>Companion matching is for adults aged 18 and over. School trips must be arranged by an authorised adult organiser through our travel team.</li><li>Accounts require verified email; age is self-declared. Neither email verification nor post review verifies identity, background or personal safety.</li><li>Use a first name or nickname. Do not publish phone numbers, social handles, exact home addresses, identity documents or payment details.</li><li>Never send money to a stranger to reserve a companion place. An accepted request is an introduction, not a booking, deposit or guaranteed trip.</li><li>Meet in a public place, tell someone you trust about your plans and independently confirm travel arrangements.</li><li>Respect boundaries. No harassment, romantic pressure, scams or discriminatory content. Use Report or Block; review is not an emergency service.</li></ul><a href="#/privacy">Read the privacy policy ↗</a></details>`;
function compose(){const today=new Date().toISOString().slice(0,10);return `<details class="td-compose"><summary>＋ Post your travel plan</summary><p>Share an outline for moderator review. Contact details stay out of your post.</p><form id="td-create" class="td-form"><label>Public first name or nickname<input name="display_name" required minlength="2" maxlength="35" autocomplete="off"></label><label>Trip title<input name="title" required minlength="8" maxlength="90" placeholder="A slow weekend exploring Kalimpong"></label><label>Destination<select name="destination" required>${options()}</select></label><label>Travel style<select name="style">${styleOptions()}</select></label><label>Departure date<input name="start_date" type="date" min="${today}" required></label><label>Return date<input name="end_date" type="date" min="${today}" required></label><label>Estimated total budget per person · ₹<input name="budget" type="number" min="500" max="500000" step="1" required placeholder="5000"></label><label>Companion places<input name="seats" type="number" min="1" max="8" value="1" required></label><label class="td-wide">What would you like to do?<textarea name="description" required minlength="30" maxlength="700" rows="4" placeholder="Share your pace, interests, inclusions in your estimated budget and the kind of trip you have in mind."></textarea></label><label class="td-check td-wide"><input name="adult" type="checkbox" required> I am 18 or older.</label><label class="td-check td-wide"><input name="guidelines" type="checkbox" required> I accept the companion guidelines and understand this is not a booking.</label><button class="button" type="submit">Submit for review ↗</button><p class="td-wide td-feedback" role="status"></p></form></details>`;}
function tripCard(t,view){return `<article class="td-card"><div class="td-card-top"><span class="eyebrow">${esc(styles[t.style])}</span><span class="td-badge">${view==='browse'?'Email verified':esc(t.status)}</span></div><h3>${esc(t.title)}</h3><p class="td-place">↗ ${esc(name(t.destination))}</p><dl><div><dt>Travel window</dt><dd>${esc(t.start_date)} → ${esc(t.end_date)}</dd></div><div><dt>Estimated budget / person</dt><dd>${money(t.budget)}</dd></div><div><dt>Companion places</dt><dd>${view==='browse'?Math.max(0,t.seats-(t.accepted||0)):t.seats}</dd></div></dl><p class="td-description">${esc(t.description)}</p><p class="td-byline">Posted by ${esc(t.display_name)} · ${view==='browse'?'Post reviewed; identity not verified':'Your trip outline'}</p>${view==='browse'?`<details class="td-join"><summary>Request to join ↗</summary><form data-join="${t.id}" class="td-form"><label class="td-wide">Public first name or nickname<input name="display_name" required minlength="2" maxlength="35"></label><label class="td-wide">Introduce yourself<textarea name="message" required minlength="15" maxlength="400" rows="3" placeholder="Share your interests and availability. No contact details."></textarea></label><label class="td-check td-wide"><input name="adult" type="checkbox" required> I am 18 or older.</label><label class="td-check td-wide"><input name="guidelines" type="checkbox" required> I accept the companion guidelines.</label><button class="button" type="submit">Send request</button><p role="status" class="td-feedback td-wide"></p></form></details><div class="td-card-actions"><button type="button" class="text-button" data-action="block" data-id="${t.id}">Block organiser</button><details><summary>Report</summary><form data-report="${t.id}"><label>Reason<select name="reason"><option value="scam">Suspected scam</option><option value="harassment">Harassment</option><option value="contact">Exposed personal details</option><option value="underage">Underage participation</option><option value="other">Other guideline concern</option></select></label><button class="button small">Submit report</button><p class="td-feedback" role="status"></p></form></details></div>`:view==='review'?`<div class="td-card-actions"><button class="button small" data-action="moderate" data-id="${t.id}" data-status="published">Publish</button><button class="button outline small" data-action="moderate" data-id="${t.id}" data-status="rejected">Reject</button></div>`:['pending','published'].includes(t.status)?`<button class="text-button" data-action="close" data-id="${t.id}">Close this plan</button>`:''}</article>`;}
export async function renderTravelDate(main){
 const hash=location.hash;const active=()=>location.hash===hash&&main.querySelector('#td-community');
 document.title='Travel Date — Find your travel companions | KuboVistas';
 main.innerHTML=`<section class="wrap td-hero"><div><a class="back-link" href="#/">← KuboVistas</a><span class="eyebrow green">TRAVEL DATE / FIND YOUR TRAVEL PEOPLE</span><h1>A shared date.<br>A new place.<br><em>A story together.</em></h1><p>Same destination. Similar dates. A budget that fits. Meet fellow travellers who want to discover India with the same curiosity as you.</p><p class="td-definition">A travel-companion finder — for shared journeys, not romantic matchmaking.</p><a class="button" href="#td-community" id="td-explore">Find my travel people ↓</a><div class="td-tags"><span>Adults 18+</span><span>Reviewed posts</span><span>No public contact details</span></div></div><div class="td-passport"><span class="eyebrow">THE NEXT CHAPTER</span><div class="td-stamp">INDIA<br><small>EXPLORE TOGETHER</small></div><div class="td-route"><span>Your curiosity</span><b aria-hidden="true">⋮</b><span>A shared journey</span></div><p>Go for the place.<br><em>Come back with a story.</em></p><span class="td-ticket">KUBOVISTAS · TRAVEL DATE</span></div></section><section class="wrap td-steps" aria-label="How Travel Date works"><article><span>01 / SHARE</span><h2>Pick your direction.</h2><p>Post your destination, dates and estimated budget for review.</p></article><article><span>02 / CONNECT</span><h2>Find common ground.</h2><p>Request to join. The organiser chooses which requests to accept.</p></article><article><span>03 / PLAN</span><h2>Make a thoughtful plan.</h2><p>Ask our team to coordinate an introduction. Confirm arrangements separately.</p></article></section><section class="wrap td-community" id="td-community"><div class="td-section-heading"><div><span class="eyebrow green">PEOPLE WITH PLACES IN MIND</span><h2>Find your <em>shared direction.</em></h2></div><span class="td-badge">Budget is an estimate, not a quote</span></div>${guidelines}<div id="td-state" role="status">Checking companion availability…</div><div id="td-workspace"></div></section>${travelTogetherSection()}`;
 main.querySelector('#td-explore').onclick=e=>{e.preventDefault();main.querySelector('#td-community').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});main.querySelector('#td-community').setAttribute('tabindex','-1');main.querySelector('#td-community').focus({preventScroll:true});};
 let session;try{session=await getAccountSession();}catch{}if(!active())return;
 const state=main.querySelector('#td-state'),workspace=main.querySelector('#td-workspace');
 if(!session?.user){state.innerHTML=`<div class="td-empty"><h3>Your next travel story starts with you.</h3><p>Sign in and verify your email to view real companion plans or share your own. We do not display invented travellers or matches.</p><a class="button" href="#/login?return=${encodeURIComponent('/travel-date')}">Sign in to connect ↗</a></div>`;return;}
 if(!session.user.emailVerified){state.textContent='Verify your account email before viewing or posting companion plans.';return;}
 let view='browse',data;
 async function load(){
  state.textContent='Loading travel plans…';
  try{data=await api(view);if(!active())return;if(!data.available){workspace.replaceChildren();state.innerHTML='<div class="td-empty"><h3>Companion matching is getting ready.</h3><p>Posting and requests are not open yet. Our travel team can help with your plans in the meantime.</p><a class="button" href="#/contact">Talk to KuboVistas ↗</a></div>';return;}state.textContent='';draw();}catch(e){if(active()){state.textContent=e.message;workspace.innerHTML='<button type="button" class="button outline" id="td-retry">Try again</button>';workspace.querySelector('#td-retry').onclick=load;}}
 }
 function draw(){
  workspace.innerHTML=`<div class="td-tabs" role="group" aria-label="Companion views">${[['browse','Explore plans'],['mine','My plans & requests'],...(data.admin?[['review','Moderation']]:[])].map(([v,l])=>`<button class="chip ${v===view?'active':''}" type="button" data-view="${v}" aria-pressed="${v===view}">${l}</button>`).join('')}</div>${view!=='review'?compose():''}${view==='browse'?`<form id="td-filters" class="td-filters"><label>Destination<select name="destination">${options(true)}</select></label><label>Travel style<select name="style">${styleOptions(true)}</select></label><label>Available from<input name="start" type="date"></label><label>Available until<input name="end" type="date"></label><label>Maximum budget · ₹<input name="budget" type="number" min="500" step="1" placeholder="Any budget"></label><button type="reset" class="text-button">Reset filters</button></form>`:''}<p id="td-count" role="status"></p><div class="td-grid" id="td-results"></div><div id="td-requests"></div><p id="td-action-status" role="status"></p>`;
  workspace.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;load();});
  const filter=workspace.querySelector('#td-filters');
  const renderCards=()=>{const f=filter?Object.fromEntries(new FormData(filter)):{};const trips=data.trips.filter(t=>(!f.destination||t.destination===f.destination)&&(!f.style||t.style===f.style)&&(!f.start||t.end_date>=f.start)&&(!f.end||t.start_date<=f.end)&&(!f.budget||t.budget<=Number(f.budget)));const invalid=f.start&&f.end&&f.start>f.end;workspace.querySelector('#td-count').textContent=invalid?'Choose an end date on or after the start date.':`${trips.length} ${view==='browse'?'matching':'submitted'} travel plans · showing up to 100`;workspace.querySelector('#td-results').innerHTML=invalid?'':trips.length?trips.map(t=>tripCard(t,view)).join(''):`<div class="td-empty"><h3>${view==='browse'?'A shared journey starts with one idea.':'No plans here yet.'}</h3><p>${view==='browse'?'No plans match these filters yet. Try other dates or submit your own plan for review.':'Submitted plans and review decisions will appear here.'}</p></div>`;wireForms();};
  if(filter){filter.oninput=renderCards;filter.onreset=()=>setTimeout(renderCards,0);}renderCards();
  const requests=workspace.querySelector('#td-requests');
  if(view==='mine')requests.innerHTML=`<h3>Requests to your plans</h3><div class="td-grid">${(data.incoming||[]).map(r=>`<article class="td-card"><span class="td-badge">${esc(r.status)}</span><h4>${esc(r.title)}</h4><p>${esc(r.display_name)}: ${esc(r.message)}</p>${r.status==='pending'?`<button class="button small" data-action="respond" data-id="${r.id}" data-status="accepted">Accept</button> <button class="button outline small" data-action="respond" data-id="${r.id}" data-status="declined">Decline</button>`:''}<button class="text-button" data-action="block" data-kind="request" data-id="${r.id}">Block requester</button></article>`).join('')||'<p>No incoming requests.</p>'}</div><h3>Your join requests</h3><div class="td-grid">${(data.outgoing||[]).map(r=>`<article class="td-card"><h4>${esc(r.title)}</h4><p>Request: ${esc(r.status)} · Plan: ${esc(r.trip_status)}</p>${['pending','accepted'].includes(r.status)?`<button class="text-button" data-action="withdraw" data-id="${r.id}">Withdraw request</button>`:''}${r.status==='accepted'&&r.trip_status==='published'?`<p>Your introduction was accepted. Contact our team with trip reference ${esc(r.trip_id)} to discuss coordination. Personal contact details have not been shared.</p><a href="#/contact">Ask our team to coordinate ↗</a>`:''}</article>`).join('')||'<p>No join requests yet.</p>'}</div>`;
  if(view==='review')requests.innerHTML=`<h3>Open reports</h3>${(data.reports||[]).map(r=>`<article class="td-card"><h4>${esc(r.title)}</h4><p>${esc(r.reason)} · ${esc(r.trip_status)}</p><p>Posted by ${esc(r.display_name)}</p><p>${esc(r.description)}</p><button class="button outline small" data-action="moderate" data-id="${r.trip_id}" data-status="rejected">Remove trip</button> <button class="button small" data-action="resolve" data-id="${r.id}">Mark reviewed</button></article>`).join('')||'<p>No open reports.</p>'}<h3>Accepted introductions · staff only</h3><p>Contact both members separately and obtain their agreement before sharing contact details. An introduction does not confirm a booking.</p>${(data.introductions||[]).map(r=>`<article class="td-card"><h4>${esc(r.title)}</h4><p>Trip reference: ${esc(r.trip_id)}</p><p>Organiser: ${esc(r.organiser)} · ${esc(r.organiser_email)}</p><p>Traveller: ${esc(r.traveller)} · ${esc(r.traveller_email)}</p></article>`).join('')||'<p>No accepted introductions to coordinate.</p>'}`;
  workspace.onclick=async e=>{const b=e.target.closest('[data-action]');if(!b)return;b.disabled=true;const status=workspace.querySelector('#td-action-status');status.textContent='Saving…';try{const result=await api('',{action:b.dataset.action,id:b.dataset.id,status:b.dataset.status,kind:b.dataset.kind},b.dataset.action==='block'?'POST':'PATCH');if(!active())return;await load();if(active())main.querySelector('#td-action-status').textContent=result.message;}catch(error){if(active()){status.textContent=error.message;b.disabled=false;}}};
 }
 function wireForms(){
  workspace.querySelectorAll('#td-create,[data-join],[data-report]').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button[type="submit"],button'),feedback=form.querySelector('.td-feedback');button.disabled=true;feedback.textContent='Submitting…';const body=Object.fromEntries(new FormData(form));body.adult=body.adult==='on';body.guidelines=body.guidelines==='on';body.action=form.dataset.join?'join':form.dataset.report?'report':'create';body.id=form.dataset.join||form.dataset.report;try{const result=await api('',body);if(!active())return;feedback.textContent=body.action==='create'?'Submitted for review. Find its status in My plans & requests.':result.message;form.reset();if(body.action==='create')button.disabled=false;}catch(error){if(active()){feedback.textContent=error.message;button.disabled=false;}}});
 }
 await load();
}
