import test from 'node:test';
import assert from 'node:assert/strict';
import { validateTrip,validateJoin } from '../server/travel-date.js';
import { createTravelDateHandler } from '../api/travel-date.js';
import { destinations } from '../data.js';
const now=new Date('2026-09-22T00:00:00Z');
const valid={adult:true,guidelines:true,destination:destinations[0].id,style:'solo',start_date:'2026-10-10',end_date:'2026-10-12',budget:5000,seats:2,title:'A quiet mountain weekend',description:'Walking around the village and enjoying local food together.',display_name:'A traveller'};
test('valid trip keeps only permitted fields and ignores spoofed publication or owner',()=>{const t=validateTrip({...valid,status:'published',user_id:'someone'},now);assert.equal(t.budget,5000);assert.equal(t.status,undefined);assert.equal(t.user_id,undefined);});
test('trip dates reject invalid calendar dates, past trips, reversed dates and long durations',()=>{for(const dates of [{start_date:'2026-02-30'},{start_date:'2026-09-21'},{end_date:'2026-10-09'},{end_date:'2026-12-12'}])assert.throws(()=>validateTrip({...valid,...dates},now));});
test('adults, guidelines, known destinations and numeric limits are required',()=>{for(const patch of [{adult:false},{guidelines:false},{destination:'unknown'},{budget:0},{seats:9},{seats:1.5},{style:'school'}])assert.throws(()=>validateTrip({...valid,...patch},now));});
test('public fields reject direct phone, email, links and handles',()=>{for(const description of ['Send your details to test@example.com please','Please message +91 99999 99999 before the trip','Visit https://example.com to pay a deposit','Message me on @traveller before joining'])assert.throws(()=>validateTrip({...valid,description},now));});
test('join introductions also enforce adult attestation and contact restrictions',()=>{assert.throws(()=>validateJoin({adult:false,guidelines:true,display_name:'A traveller',message:'I would like to join this journey.'}));assert.throws(()=>validateJoin({adult:true,guidelines:true,display_name:'A traveller',message:'Send money to https://example.com'}));});
const session={user:{id:'u1',emailVerified:true}};
const base={enabled:()=>true,authConfigured:()=>true,databaseConfigured:()=>true,requireSession:async()=>session,isAdmin:()=>false};
async function call(deps,method='GET',body={},view='browse'){
 let result;const res={statusCode:200,setHeader(){},end(s){result={status:this.statusCode,body:JSON.parse(s)};}};
 await createTravelDateHandler({...base,...deps})({method,query:{view},body,headers:{}},res);return result;
}
test('disabled feature never queries or accepts submissions',async()=>{const deps={enabled:()=>false,query:()=>{throw Error('must not query');}};assert.equal((await call(deps)).body.available,false);assert.equal((await call(deps,'POST')).status,503);});
test('unverified members and non-admin moderation are rejected before database access',async()=>{const deps={query:()=>{throw Error('must not query');}};assert.equal((await call({...deps,requireSession:async()=>({user:{emailVerified:false}})})).status,403);assert.equal((await call(deps,'GET',{},'review')).status,403);assert.equal((await call(deps,'PATCH',{action:'moderate',id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',status:'published'})).status,403);});
test('browse query excludes blocked members, expired trips and private account fields',async()=>{let sql,params;await call({query:async(s,p)=>{sql=s;params=p;return {rows:[]};}});assert.match(sql,/start_date>=CURRENT_DATE/);assert.match(sql,/travel_date_blocks/);assert.match(sql,/status='published'/);assert.doesNotMatch(sql,/SELECT \*|email|phone/);assert.deepEqual(params,['u1']);});
test('only request owner can withdraw and only plan owner can close',async()=>{for(const action of ['withdraw','close']){let sql,params;const r=await call({query:async(s,p)=>{sql=s;params=p;return {rowCount:0,rows:[]};}},'PATCH',{action,id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'});assert.equal(r.status,404);assert.match(sql,/user_id=\$2/);assert.equal(params[1],'u1');}});
test('acceptance serializes on the organiser trip and rejects full capacity',async()=>{const sqls=[];const r=await call({transaction:async callback=>callback({query:async(sql)=>{sqls.push(sql);if(sql.includes('SELECT trip_id'))return {rowCount:1,rows:[{trip_id:'trip'}]};if(sql.includes('SELECT * FROM travel_date_trips'))return {rowCount:1,rows:[{id:'trip',seats:1}]};if(sql.includes('SELECT r.*'))return {rowCount:1,rows:[{id:'request'}]};if(sql.includes('count(*)'))return {rows:[{n:1}]};throw Error('must not update full trip');}})},'PATCH',{action:'respond',id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',status:'accepted'});assert.equal(r.status,409);assert.ok(sqls.some(s=>s.includes('user_id=$2')&&s.includes('FOR UPDATE')));});
