import { adsenseConfig } from './adsense-config.mjs';
import { mkdir, copyFile, cp, rm, readFile, writeFile } from 'node:fs/promises';
const ads = adsenseConfig(process.env);
const root = new URL('../',import.meta.url);
const output = new URL('dist/',root);
await rm(output,{recursive:true,force:true});
await mkdir(output,{recursive:true});
for (const name of ['adsense.js','adsense.css','index.html','styles.css','app.js','account.js','journal.js','company.js','explore.js','destination-meta.js','partner-data.js','travel-links.js','booking-ui.js','kubo.js','kubo-knowledge.js','navigation.css','kubo.css','data.js','legal.js']) await copyFile(new URL(name,root),new URL(name,output));
await cp(new URL('assets/',root),new URL('assets/',output),{recursive:true});
const html = await readFile(new URL('index.html',output),'utf8');
await writeFile(new URL('index.html',output),html.replace('<!-- ADSENSE_CONFIG -->',ads.head));
await writeFile(new URL('ads.txt',output),ads.adsTxt);
console.log('Production site built in dist/');
